namespace Thyt.TiPLM.UIL.Resource.Common.ResCommon {
    partial class FrmModelDef {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>

        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary> 
        ///          

        private void InitializeComponent() {
            this.panel1 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.btnOK = new Thyt.TiPLM.UIL.Controls.ButtonPLM();
            this.btnExit = new Thyt.TiPLM.UIL.Controls.ButtonPLM();
            this.splitter1 = new Thyt.TiPLM.UIL.Controls.SplitterPLM();
            this.tabControl1 = new Thyt.TiPLM.UIL.Controls.TabControlPLM();
            this.tabPage1 = new Thyt.TiPLM.UIL.Controls.TabPagePLM();
            this.panel3 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.panel6 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.panel8 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.groupBox2 = new Thyt.TiPLM.UIL.Controls.GroupBoxPLM();
            this.tV_define = new System.Windows.Forms.TreeView();
            this.panel7 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.panel9 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.groupBox4 = new Thyt.TiPLM.UIL.Controls.GroupBoxPLM();
            this.tB_Virtual = new Thyt.TiPLM.UIL.Controls.TextEditPLM();
            this.btnAddVirtual = new Thyt.TiPLM.UIL.Controls.ButtonPLM();
            this.btnSetShow = new Thyt.TiPLM.UIL.Controls.ButtonPLM();
            this.btnDel = new Thyt.TiPLM.UIL.Controls.ButtonPLM();
            this.btnAdd = new Thyt.TiPLM.UIL.Controls.ButtonPLM();
            this.groupBox1 = new Thyt.TiPLM.UIL.Controls.GroupBoxPLM();
            this.lB_Attr = new Thyt.TiPLM.UIL.Controls.ListBoxPLM();
            this.splitter2 = new Thyt.TiPLM.UIL.Controls.SplitterPLM();
            this.panel5 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.groupBox3 = new Thyt.TiPLM.UIL.Controls.GroupBoxPLM();
            this.chB_isExpand = new Thyt.TiPLM.UIL.Controls.CheckEditPLM();
            this.tabPage2 = new Thyt.TiPLM.UIL.Controls.TabPagePLM();
            this.panel4 = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.panel1.SuspendLayout();
            this.tabControl1.BeginInit();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel8.SuspendLayout();
            this.groupBox2.BeginInit();
            this.groupBox2.SuspendLayout();
            this.panel7.SuspendLayout();
            this.panel9.SuspendLayout();
            this.groupBox4.BeginInit();
            this.groupBox4.SuspendLayout();
            this.tB_Virtual.Properties.BeginInit();
            this.groupBox1.BeginInit();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)this.lB_Attr).BeginInit();
            this.panel5.SuspendLayout();
            this.groupBox3.BeginInit();
            this.groupBox3.SuspendLayout();
            this.chB_isExpand.Properties.BeginInit();
            this.tabPage2.SuspendLayout();
            base.SuspendLayout();
            this.panel1.Controls.Add(this.btnOK);
            this.panel1.Controls.Add(this.btnExit);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(0, 0x1e8);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(0x2c0, 0x22);
            this.panel1.TabIndex = 0;
            this.btnOK.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Top;
            this.btnOK.Location = new System.Drawing.Point(0x20d, 3);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(0x4b, 0x19);
            this.btnOK.TabIndex = 1;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
            this.btnExit.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Top;
            this.btnExit.Location = new System.Drawing.Point(0x269, 3);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(0x4b, 0x19);
            this.btnExit.TabIndex = 0;
            this.btnExit.Text = "取消";
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            this.splitter1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.splitter1.Location = new System.Drawing.Point(0, 0x1e3);
            this.splitter1.Name = "splitter1";
            this.splitter1.Size = new System.Drawing.Size(0x2c0, 5);
            this.splitter1.TabIndex = 1;
            this.splitter1.TabStop = false;
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedTabPage = this.tabPage1;
            this.tabControl1.Size = new System.Drawing.Size(0x2c0, 0x1e3);
            this.tabControl1.TabIndex = 0;
            this.tabControl1.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] { this.tabPage1, this.tabPage2 });
            this.tabControl1.SelectedPageChanged += new DevExpress.XtraTab.TabPageChangedEventHandler(this.tabControl1_SelectedIndexChanged);
            this.tabPage1.Controls.Add(this.panel3);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Size = new System.Drawing.Size(0x2ba, 0x1c6);
            this.tabPage1.Text = "分类定义";
            this.panel3.Controls.Add(this.panel6);
            this.panel3.Controls.Add(this.splitter2);
            this.panel3.Controls.Add(this.panel5);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(0, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(0x2ba, 0x1c6);
            this.panel3.TabIndex = 0;
            this.panel6.Controls.Add(this.panel8);
            this.panel6.Controls.Add(this.panel7);
            this.panel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel6.Location = new System.Drawing.Point(2, 2);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(0x2b6, 0x189);
            this.panel6.TabIndex = 2;
            this.panel8.Controls.Add(this.groupBox2);
            this.panel8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel8.Location = new System.Drawing.Point(0x12a, 2);
            this.panel8.Name = "panel8";
            this.panel8.Size = new System.Drawing.Size(0x18a, 0x185);
            this.panel8.TabIndex = 1;
            this.groupBox2.Controls.Add(this.tV_define);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox2.Location = new System.Drawing.Point(2, 2);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(390, 0x181);
            this.groupBox2.TabIndex = 0;
            this.groupBox2.Text = "类主键";
            this.tV_define.CheckBoxes = true;
            this.tV_define.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tV_define.Location = new System.Drawing.Point(2, 0x16);
            this.tV_define.Name = "tV_define";
            this.tV_define.Size = new System.Drawing.Size(0x182, 0x169);
            this.tV_define.TabIndex = 0;
            this.tV_define.BeforeCheck += new System.Windows.Forms.TreeViewCancelEventHandler(this.tV_define_BeforeCheck);
            this.panel7.Controls.Add(this.panel9);
            this.panel7.Controls.Add(this.groupBox1);
            this.panel7.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel7.Location = new System.Drawing.Point(2, 2);
            this.panel7.Name = "panel7";
            this.panel7.Size = new System.Drawing.Size(0x128, 0x185);
            this.panel7.TabIndex = 0;
            this.panel9.Controls.Add(this.groupBox4);
            this.panel9.Controls.Add(this.btnSetShow);
            this.panel9.Controls.Add(this.btnDel);
            this.panel9.Controls.Add(this.btnAdd);
            this.panel9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel9.Location = new System.Drawing.Point(0xca, 2);
            this.panel9.Name = "panel9";
            this.panel9.Size = new System.Drawing.Size(0x5c, 0x181);
            this.panel9.TabIndex = 1;
            this.groupBox4.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom;
            this.groupBox4.Controls.Add(this.tB_Virtual);
            this.groupBox4.Controls.Add(this.btnAddVirtual);
            this.groupBox4.Location = new System.Drawing.Point(4, 0x126);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(0x54, 0x5e);
            this.groupBox4.TabIndex = 4;
            this.groupBox4.Text = "虚拟主键";
            this.tB_Virtual.Location = new System.Drawing.Point(8, 0x1a);
            this.tB_Virtual.Name = "tB_Virtual";
            this.tB_Virtual.Size = new System.Drawing.Size(0x48, 0x16);
            this.tB_Virtual.TabIndex = 4;
            this.btnAddVirtual.Location = new System.Drawing.Point(12, 60);
            this.btnAddVirtual.Name = "btnAddVirtual";
            this.btnAddVirtual.Size = new System.Drawing.Size(0x40, 0x1a);
            this.btnAddVirtual.TabIndex = 3;
            this.btnAddVirtual.Text = "增加";
            this.btnAddVirtual.Click += new System.EventHandler(this.btnAddVirtual_Click);
            this.btnSetShow.Location = new System.Drawing.Point(14, 0xce);
            this.btnSetShow.Name = "btnSetShow";
            this.btnSetShow.Size = new System.Drawing.Size(0x47, 0x18);
            this.btnSetShow.TabIndex = 3;
            this.btnSetShow.Text = "显示/隐藏";
            this.btnSetShow.Click += new System.EventHandler(this.btnSetShow_Click);
            this.btnDel.Location = new System.Drawing.Point(14, 0x4d);
            this.btnDel.Name = "btnDel";
            this.btnDel.Size = new System.Drawing.Size(0x40, 0x1a);
            this.btnDel.TabIndex = 1;
            this.btnDel.Text = "<";
            this.btnDel.Click += new System.EventHandler(this.btnDel_Click);
            this.btnAdd.Location = new System.Drawing.Point(14, 0x1a);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(0x40, 0x19);
            this.btnAdd.TabIndex = 0;
            this.btnAdd.Text = ">";
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.groupBox1.Controls.Add(this.lB_Attr);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Left;
            this.groupBox1.Location = new System.Drawing.Point(2, 2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(200, 0x181);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.Text = "类属性";
            this.lB_Attr.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lB_Attr.ItemHeight = 0x10;
            this.lB_Attr.Location = new System.Drawing.Point(2, 0x16);
            this.lB_Attr.Name = "lB_Attr";
            this.lB_Attr.Size = new System.Drawing.Size(0xc4, 0x169);
            this.lB_Attr.TabIndex = 0;
            this.splitter2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.splitter2.Location = new System.Drawing.Point(2, 0x18b);
            this.splitter2.Name = "splitter2";
            this.splitter2.Size = new System.Drawing.Size(0x2b6, 5);
            this.splitter2.TabIndex = 1;
            this.splitter2.TabStop = false;
            this.panel5.Controls.Add(this.groupBox3);
            this.panel5.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel5.Location = new System.Drawing.Point(2, 400);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(0x2b6, 0x34);
            this.panel5.TabIndex = 0;
            this.groupBox3.Controls.Add(this.chB_isExpand);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox3.Location = new System.Drawing.Point(2, 2);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(690, 0x30);
            this.groupBox3.TabIndex = 0;
            this.groupBox3.Text = "模型属性";
            this.chB_isExpand.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Top;
            this.chB_isExpand.Enabled = false;
            this.chB_isExpand.Location = new System.Drawing.Point(0x1d3, 0x17);
            this.chB_isExpand.Name = "chB_isExpand";
            this.chB_isExpand.Properties.Caption = "分类主键全部展开显示";
            this.chB_isExpand.Size = new System.Drawing.Size(0xda, 0x13);
            this.chB_isExpand.TabIndex = 0;
            this.chB_isExpand.CheckedChanged += new System.EventHandler(this.chB_isExpand_CheckedChanged);
            this.tabPage2.Controls.Add(this.panel4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Size = new System.Drawing.Size(0x2ba, 0x1c6);
            this.tabPage2.Text = "预览";
            this.panel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel4.Location = new System.Drawing.Point(0, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(0x2ba, 0x1c6);
            this.panel4.TabIndex = 0;
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 15);
            base.ClientSize = new System.Drawing.Size(0x2c0, 0x20a);
            base.Controls.Add(this.tabControl1);
            base.Controls.Add(this.splitter1);
            base.Controls.Add(this.panel1);
            base.Name = "FrmModelDef";
            base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "模型定义";
            base.Load += new System.EventHandler(this.FrmModelDef_Load);
            this.panel1.ResumeLayout(false);
            this.tabControl1.EndInit();
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel6.ResumeLayout(false);
            this.panel8.ResumeLayout(false);
            this.groupBox2.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.panel7.ResumeLayout(false);
            this.panel9.ResumeLayout(false);
            this.groupBox4.EndInit();
            this.groupBox4.ResumeLayout(false);
            this.tB_Virtual.Properties.EndInit();
            this.groupBox1.EndInit();
            this.groupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)this.lB_Attr).EndInit();
            this.panel5.ResumeLayout(false);
            this.groupBox3.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.chB_isExpand.Properties.EndInit();
            this.tabPage2.ResumeLayout(false);
            base.ResumeLayout(false);
        }
        #endregion    
        private Thyt.TiPLM.UIL.Controls.ButtonPLM btnAdd;
        private Thyt.TiPLM.UIL.Controls.ButtonPLM btnAddVirtual;
        private Thyt.TiPLM.UIL.Controls.ButtonPLM btnDel;
        private Thyt.TiPLM.UIL.Controls.ButtonPLM btnExit;
        private Thyt.TiPLM.UIL.Controls.ButtonPLM btnOK;
        private Thyt.TiPLM.UIL.Controls.ButtonPLM btnSetShow;
        private Thyt.TiPLM.UIL.Controls.CheckEditPLM chB_isExpand;
        private Thyt.TiPLM.UIL.Controls.GroupBoxPLM groupBox1;
        private Thyt.TiPLM.UIL.Controls.GroupBoxPLM groupBox2;
        private Thyt.TiPLM.UIL.Controls.GroupBoxPLM groupBox3;
        private Thyt.TiPLM.UIL.Controls.GroupBoxPLM groupBox4;
        private Thyt.TiPLM.UIL.Controls.ListBoxPLM lB_Attr;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel1;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel3;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel4;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel5;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel6;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel7;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel8;
        private Thyt.TiPLM.UIL.Controls.PanelPLM panel9;
        private Thyt.TiPLM.UIL.Controls.SplitterPLM splitter1;
        private Thyt.TiPLM.UIL.Controls.SplitterPLM splitter2;
        private Thyt.TiPLM.UIL.Controls.TabControlPLM tabControl1;
        private Thyt.TiPLM.UIL.Controls.TabPagePLM tabPage1;
        private Thyt.TiPLM.UIL.Controls.TabPagePLM tabPage2;
        private Thyt.TiPLM.UIL.Controls.TextEditPLM tB_Virtual;
        private System.Windows.Forms.TreeView tV_define;
    }
}