namespace Thyt.TiPLM.UIL.PPM.PPCardModeling {
    partial class DlgOption2 {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary> 
        ///     
        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DlgOption2));
            Infragistics.Win.Appearance appearance = new Infragistics.Win.Appearance();
            this.tbcData = new System.Windows.Forms.TabControl();
            this.tabBinding = new System.Windows.Forms.TabPage();
            this.grpArea = new System.Windows.Forms.GroupBox();
            this.btnSubKeyExplain = new System.Windows.Forms.Button();
            this.chkSubKey = new System.Windows.Forms.CheckBox();
            this.chkKey = new System.Windows.Forms.CheckBox();
            this.rbtTail = new System.Windows.Forms.RadioButton();
            this.rbtMid = new System.Windows.Forms.RadioButton();
            this.rbtHead = new System.Windows.Forms.RadioButton();
            this.grpBinding = new System.Windows.Forms.GroupBox();
            this.ultraEditor =new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.label12 = new System.Windows.Forms.Label();
            this.btnSmartConfig = new System.Windows.Forms.Button();
            this.cobAttrList = new System.Windows.Forms.ComboBox();
            this.txtType = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.txtField = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.pnlGrid = new System.Windows.Forms.Panel();
            this.chkGridReturn = new System.Windows.Forms.CheckBox();
            this.txtGridEnd = new System.Windows.Forms.TextBox();
            this.txtGridStart = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.pnlBool = new System.Windows.Forms.Panel();
            this.cobBool = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.pnlString = new System.Windows.Forms.Panel();
            this.numReturnRows = new System.Windows.Forms.NumericUpDown();
            this.chkReturn = new System.Windows.Forms.CheckBox();
            this.numJumpPage = new System.Windows.Forms.NumericUpDown();
            this.label11 = new System.Windows.Forms.Label();
            this.tvwType = new System.Windows.Forms.TreeView();
            this.tabScript = new System.Windows.Forms.TabPage();
            this.rtxScript = new System.Windows.Forms.RichTextBox();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOK = new System.Windows.Forms.Button();
            this.cmbTemplate = new System.Windows.Forms.ComboBox();
            this.chkBarcode = new System.Windows.Forms.CheckBox();
            this.tbcData.SuspendLayout();
            this.tabBinding.SuspendLayout();
            this.grpArea.SuspendLayout();
            this.grpBinding.SuspendLayout();
            this.pnlGrid.SuspendLayout();
            this.pnlBool.SuspendLayout();
            this.pnlString.SuspendLayout();
            this.numReturnRows.BeginInit();
            this.numJumpPage.BeginInit();
            this.tabScript.SuspendLayout();
            base.SuspendLayout();
            this.tbcData.Controls.Add(this.tabBinding);
            this.tbcData.Controls.Add(this.tabScript);
            resources.ApplyResources(this.tbcData, "tbcData");
            this.tbcData.Multiline = true;
            this.tbcData.Name = "tbcData";
            this.tbcData.SelectedIndex = 0;
            this.tbcData.Tag = "";
            this.tbcData.SelectedIndexChanged += new System.EventHandler(this.tbcData_SelectedIndexChanged);
            this.tabBinding.Controls.Add(this.grpArea);
            this.tabBinding.Controls.Add(this.grpBinding);
            this.tabBinding.Controls.Add(this.tvwType);
            resources.ApplyResources(this.tabBinding, "tabBinding");
            this.tabBinding.Name = "tabBinding";
            this.tabBinding.Tag = "Binding";
            resources.ApplyResources(this.grpArea, "grpArea");
            this.grpArea.Controls.Add(this.btnSubKeyExplain);
            this.grpArea.Controls.Add(this.chkSubKey);
            this.grpArea.Controls.Add(this.chkKey);
            this.grpArea.Controls.Add(this.rbtTail);
            this.grpArea.Controls.Add(this.rbtMid);
            this.grpArea.Controls.Add(this.rbtHead);
            this.grpArea.Name = "grpArea";
            this.grpArea.TabStop = false;
            this.btnSubKeyExplain.ForeColor = System.Drawing.Color.Black;
            resources.ApplyResources(this.btnSubKeyExplain, "btnSubKeyExplain");
            this.btnSubKeyExplain.Name = "btnSubKeyExplain";
            this.btnSubKeyExplain.UseVisualStyleBackColor = true;
            this.btnSubKeyExplain.Click += new System.EventHandler(this.btnSubKeyExplain_Click);
            resources.ApplyResources(this.chkSubKey, "chkSubKey");
            this.chkSubKey.ForeColor = System.Drawing.Color.Black;
            this.chkSubKey.Name = "chkSubKey";
            this.chkSubKey.CheckedChanged += new System.EventHandler(this.chkSubKey_CheckedChanged);
            resources.ApplyResources(this.chkKey, "chkKey");
            this.chkKey.ForeColor = System.Drawing.Color.Red;
            this.chkKey.Name = "chkKey";
            this.chkKey.CheckedChanged += new System.EventHandler(this.chkKey_CheckedChanged);
            resources.ApplyResources(this.rbtTail, "rbtTail");
            this.rbtTail.Name = "rbtTail";
            resources.ApplyResources(this.rbtMid, "rbtMid");
            this.rbtMid.Checked = true;
            this.rbtMid.Name = "rbtMid";
            this.rbtMid.TabStop = true;
            resources.ApplyResources(this.rbtHead, "rbtHead");
            this.rbtHead.Name = "rbtHead";
            resources.ApplyResources(this.grpBinding, "grpBinding");
            this.grpBinding.Controls.Add(this.pnlString);
            this.grpBinding.Controls.Add(this.ultraEditor);
            this.grpBinding.Controls.Add(this.label12);
            this.grpBinding.Controls.Add(this.btnSmartConfig);
            this.grpBinding.Controls.Add(this.cobAttrList);
            this.grpBinding.Controls.Add(this.txtType);
            this.grpBinding.Controls.Add(this.label7);
            this.grpBinding.Controls.Add(this.label6);
            this.grpBinding.Controls.Add(this.txtField);
            this.grpBinding.Controls.Add(this.label5);
            this.grpBinding.Controls.Add(this.pnlGrid);
            this.grpBinding.Controls.Add(this.pnlBool);
            this.grpBinding.Name = "grpBinding";
            this.grpBinding.TabStop = false;
            this.ultraEditor.AlwaysInEditMode = true;
            resources.ApplyResources(this.ultraEditor, "ultraEditor");
            appearance.FontData.Bold = (Infragistics.Win.DefaultableBoolean)resources.GetObject("resource.Bold");
            appearance.FontData.Italic = (Infragistics.Win.DefaultableBoolean)resources.GetObject("resource.Italic");
            appearance.FontData.Name = resources.GetString("resource.Name");
            appearance.FontData.SizeInPoints = (float)resources.GetObject("resource.SizeInPoints");
            appearance.FontData.Strikeout = (Infragistics.Win.DefaultableBoolean)resources.GetObject("resource.Strikeout");
            appearance.FontData.Underline = (Infragistics.Win.DefaultableBoolean)resources.GetObject("resource.Underline");
            this.ultraEditor.Appearance = appearance;
            this.ultraEditor.HideSelection = false;
            this.ultraEditor.MaxLength = 0x80;
            this.ultraEditor.Name = "ultraEditor";
            this.ultraEditor.ReadOnly = true;
            this.ultraEditor.SupportThemes = false;
            resources.ApplyResources(this.label12, "label12");
            this.label12.Name = "label12";
            resources.ApplyResources(this.btnSmartConfig, "btnSmartConfig");
            this.btnSmartConfig.Name = "btnSmartConfig";
            this.cobAttrList.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cobAttrList, "cobAttrList");
            this.cobAttrList.Name = "cobAttrList";
            this.cobAttrList.SelectionChangeCommitted += new System.EventHandler(this.cobAttrList_SelectionChangeCommitted);
            resources.ApplyResources(this.txtType, "txtType");
            this.txtType.Name = "txtType";
            this.txtType.ReadOnly = true;
            resources.ApplyResources(this.label7, "label7");
            this.label7.Name = "label7";
            resources.ApplyResources(this.label6, "label6");
            this.label6.Name = "label6";
            resources.ApplyResources(this.txtField, "txtField");
            this.txtField.Name = "txtField";
            this.txtField.ReadOnly = true;
            resources.ApplyResources(this.label5, "label5");
            this.label5.Name = "label5";
            this.pnlGrid.Controls.Add(this.chkGridReturn);
            this.pnlGrid.Controls.Add(this.txtGridEnd);
            this.pnlGrid.Controls.Add(this.txtGridStart);
            this.pnlGrid.Controls.Add(this.label3);
            resources.ApplyResources(this.pnlGrid, "pnlGrid");
            this.pnlGrid.Name = "pnlGrid";
            resources.ApplyResources(this.chkGridReturn, "chkGridReturn");
            this.chkGridReturn.Name = "chkGridReturn";
            this.txtGridEnd.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            resources.ApplyResources(this.txtGridEnd, "txtGridEnd");
            this.txtGridEnd.Name = "txtGridEnd";
            this.txtGridStart.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            resources.ApplyResources(this.txtGridStart, "txtGridStart");
            this.txtGridStart.Name = "txtGridStart";
            this.txtGridStart.ReadOnly = true;
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            this.pnlBool.Controls.Add(this.cobBool);
            this.pnlBool.Controls.Add(this.label2);
            resources.ApplyResources(this.pnlBool, "pnlBool");
            this.pnlBool.Name = "pnlBool";
            this.cobBool.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cobBool, "cobBool");
            this.cobBool.Name = "cobBool";
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            this.pnlString.Controls.Add(this.cmbTemplate);
            this.pnlString.Controls.Add(this.chkBarcode);
            this.pnlString.Controls.Add(this.numReturnRows);
            this.pnlString.Controls.Add(this.chkReturn);
            this.pnlString.Controls.Add(this.numJumpPage);
            this.pnlString.Controls.Add(this.label11);
            resources.ApplyResources(this.pnlString, "pnlString");
            this.pnlString.Name = "pnlString";
            resources.ApplyResources(this.numReturnRows, "numReturnRows");
            int[] bits = new int[4];
            bits[0] = 200;
            this.numReturnRows.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 1;
            this.numReturnRows.Minimum = new decimal(numArray2);
            this.numReturnRows.Name = "numReturnRows";
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.numReturnRows.Value = new decimal(numArray3);
            resources.ApplyResources(this.chkReturn, "chkReturn");
            this.chkReturn.Name = "chkReturn";
            this.chkReturn.CheckedChanged += new System.EventHandler(this.chkReturn_CheckedChanged);
            resources.ApplyResources(this.numJumpPage, "numJumpPage");
            int[] numArray4 = new int[4];
            numArray4[0] = 200;
            this.numJumpPage.Maximum = new decimal(numArray4);
            this.numJumpPage.Name = "numJumpPage";
            resources.ApplyResources(this.label11, "label11");
            this.label11.Name = "label11";
            resources.ApplyResources(this.tvwType, "tvwType");
            this.tvwType.ItemHeight = 14;
            this.tvwType.Name = "tvwType";
            this.tvwType.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.tvwType_AfterSelect);
            this.tabScript.Controls.Add(this.rtxScript);
            resources.ApplyResources(this.tabScript, "tabScript");
            this.tabScript.Name = "tabScript";
            this.tabScript.Tag = "Script";
            resources.ApplyResources(this.rtxScript, "rtxScript");
            this.rtxScript.Name = "rtxScript";
            this.rtxScript.ReadOnly = true;
            resources.ApplyResources(this.btnCancel, "btnCancel");
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Name = "btnCancel";
            resources.ApplyResources(this.btnOK, "btnOK");
            this.btnOK.Name = "btnOK";
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
            this.cmbTemplate.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cmbTemplate, "cmbTemplate");
            this.cmbTemplate.Name = "cmbTemplate";
            resources.ApplyResources(this.chkBarcode, "chkBarcode");
            this.chkBarcode.Name = "chkBarcode";
            this.chkBarcode.CheckedChanged += new System.EventHandler(this.chkBarcode_CheckedChanged);
            resources.ApplyResources(this, "$this");
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.tbcData);
            base.Controls.Add(this.btnCancel);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "DlgOption2";
            base.ShowInTaskbar = false;
            base.Load += new System.EventHandler(this.DlgOption2_Load);
            this.tbcData.ResumeLayout(false);
            this.tabBinding.ResumeLayout(false);
            this.grpArea.ResumeLayout(false);
            this.grpArea.PerformLayout();
            this.grpBinding.ResumeLayout(false);
            this.grpBinding.PerformLayout();
            this.pnlGrid.ResumeLayout(false);
            this.pnlGrid.PerformLayout();
            this.pnlBool.ResumeLayout(false);
            this.pnlString.ResumeLayout(false);
            this.numReturnRows.EndInit();
            this.numJumpPage.EndInit();
            this.tabScript.ResumeLayout(false);
            base.ResumeLayout(false);
        } 

        #endregion      
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOK;
        private System.Windows.Forms.Button btnSmartConfig;
        private System.Windows.Forms.Button btnSubKeyExplain;
        private System.Windows.Forms.CheckBox chkBarcode;
        private System.Windows.Forms.CheckBox chkGridReturn;
        private System.Windows.Forms.CheckBox chkKey;
        private System.Windows.Forms.CheckBox chkReturn;
        private System.Windows.Forms.CheckBox chkSubKey;
        private System.Windows.Forms.ComboBox cmbTemplate;
        private System.Windows.Forms.ComboBox cobAttrList;
        private System.Windows.Forms.ComboBox cobBool;
        private System.Windows.Forms.GroupBox grpArea;
        private System.Windows.Forms.GroupBox grpBinding;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.NumericUpDown numJumpPage;
        private System.Windows.Forms.NumericUpDown numReturnRows;
        private System.Windows.Forms.Panel pnlBool;
        private System.Windows.Forms.Panel pnlGrid;
        private System.Windows.Forms.Panel pnlString;
        private System.Windows.Forms.RadioButton rbtHead;
        private System.Windows.Forms.RadioButton rbtMid;
        private System.Windows.Forms.RadioButton rbtTail;
        private System.Windows.Forms.TabPage tabBinding;
        private System.Windows.Forms.TabPage tabScript;
        private System.Windows.Forms.TabControl tbcData;
        private System.Windows.Forms.TreeView tvwType;
        private System.Windows.Forms.TextBox txtField;
        private System.Windows.Forms.TextBox txtGridEnd;
        private System.Windows.Forms.TextBox txtGridStart;
        private System.Windows.Forms.TextBox txtType;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor ultraEditor;

    }
}