namespace Thyt.TiPLM.UIL.PPM.PPCardModeling {
    partial class DlgPageSetup {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary> 
        ///      

        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DlgPageSetup));
            this.tcl_PageSetting = new System.Windows.Forms.TabControl();
            this.tpg_Page = new System.Windows.Forms.TabPage();
            this.rdb_Landscape = new System.Windows.Forms.RadioButton();
            this.pcb_OritationLandscape = new System.Windows.Forms.PictureBox();
            this.pcb_OritationPortrait = new System.Windows.Forms.PictureBox();
            this.rdb_Portrait = new System.Windows.Forms.RadioButton();
            this.txb_StartPage = new System.Windows.Forms.TextBox();
            this.cbb_PaintQuality = new System.Windows.Forms.ComboBox();
            this.cbb_PageSize = new System.Windows.Forms.ComboBox();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label2 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.rdb_Zoom = new System.Windows.Forms.RadioButton();
            this.rdb_Adjust = new System.Windows.Forms.RadioButton();
            this.npd_PageHigh = new System.Windows.Forms.NumericUpDown();
            this.npd_PageWidth = new System.Windows.Forms.NumericUpDown();
            this.npd_Zoom = new System.Windows.Forms.NumericUpDown();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.tpg_Margin = new System.Windows.Forms.TabPage();
            this.pcb_Margin = new System.Windows.Forms.PictureBox();
            this.label15 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.ckb_Vertical = new System.Windows.Forms.CheckBox();
            this.ckb_Level = new System.Windows.Forms.CheckBox();
            this.label9 = new System.Windows.Forms.Label();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.npd_FooterMargin = new System.Windows.Forms.NumericUpDown();
            this.npd_HeaderMargin = new System.Windows.Forms.NumericUpDown();
            this.npd_RightMargin = new System.Windows.Forms.NumericUpDown();
            this.npd_LeftMargin = new System.Windows.Forms.NumericUpDown();
            this.npd_BottomMargin = new System.Windows.Forms.NumericUpDown();
            this.npd_TopMargin = new System.Windows.Forms.NumericUpDown();
            this.tpg_HeaderFooter = new System.Windows.Forms.TabPage();
            this.label17 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.txb_Footer = new System.Windows.Forms.TextBox();
            this.cbb_Footer = new System.Windows.Forms.ComboBox();
            this.btn_CustomFooter = new System.Windows.Forms.Button();
            this.btn_CustomHeader = new System.Windows.Forms.Button();
            this.cbb_Header = new System.Windows.Forms.ComboBox();
            this.txb_Header = new System.Windows.Forms.TextBox();
            this.tpg_Table = new System.Windows.Forms.TabPage();
            this.chk_ShrinkToFit = new System.Windows.Forms.CheckBox();
            this.cbb_PrintWrongCell = new System.Windows.Forms.ComboBox();
            this.cbb_Postil = new System.Windows.Forms.ComboBox();
            this.pcb_PrintOrder = new System.Windows.Forms.PictureBox();
            this.rdb_RowFirst = new System.Windows.Forms.RadioButton();
            this.rdb_ListFirst = new System.Windows.Forms.RadioButton();
            this.label24 = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.ckb_RowList = new System.Windows.Forms.CheckBox();
            this.ckb_PrintAsDraft = new System.Windows.Forms.CheckBox();
            this.ckb_SingleColor = new System.Windows.Forms.CheckBox();
            this.ckb_GridLine = new System.Windows.Forms.CheckBox();
            this.label20 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.panel3 = new System.Windows.Forms.Panel();
            this.btn_Ensure = new System.Windows.Forms.Button();
            this.btn_Cancel = new System.Windows.Forms.Button();
            this.tcl_PageSetting.SuspendLayout();
            this.tpg_Page.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)this.pcb_OritationLandscape).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.pcb_OritationPortrait).BeginInit();
            this.panel2.SuspendLayout();
            this.npd_PageHigh.BeginInit();
            this.npd_PageWidth.BeginInit();
            this.npd_Zoom.BeginInit();
            this.tpg_Margin.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)this.pcb_Margin).BeginInit();
            this.npd_FooterMargin.BeginInit();
            this.npd_HeaderMargin.BeginInit();
            this.npd_RightMargin.BeginInit();
            this.npd_LeftMargin.BeginInit();
            this.npd_BottomMargin.BeginInit();
            this.npd_TopMargin.BeginInit();
            this.tpg_HeaderFooter.SuspendLayout();
            this.tpg_Table.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)this.pcb_PrintOrder).BeginInit();
            base.SuspendLayout();
            this.tcl_PageSetting.Controls.Add(this.tpg_Page);
            this.tcl_PageSetting.Controls.Add(this.tpg_Margin);
            this.tcl_PageSetting.Controls.Add(this.tpg_HeaderFooter);
            this.tcl_PageSetting.Controls.Add(this.tpg_Table);
            this.tcl_PageSetting.ItemSize = new System.Drawing.Size(60, 20);
            this.tcl_PageSetting.Location = new System.Drawing.Point(6, 6);
            this.tcl_PageSetting.Multiline = true;
            this.tcl_PageSetting.Name = "tcl_PageSetting";
            this.tcl_PageSetting.SelectedIndex = 0;
            this.tcl_PageSetting.Size = new System.Drawing.Size(0x16a, 0x102);
            this.tcl_PageSetting.TabIndex = 0;
            this.tcl_PageSetting.SelectedIndexChanged += new System.EventHandler(this.tcl_PageSetting_SelectedIndexChanged);
            this.tpg_Page.Controls.Add(this.rdb_Landscape);
            this.tpg_Page.Controls.Add(this.pcb_OritationLandscape);
            this.tpg_Page.Controls.Add(this.pcb_OritationPortrait);
            this.tpg_Page.Controls.Add(this.rdb_Portrait);
            this.tpg_Page.Controls.Add(this.txb_StartPage);
            this.tpg_Page.Controls.Add(this.cbb_PaintQuality);
            this.tpg_Page.Controls.Add(this.cbb_PageSize);
            this.tpg_Page.Controls.Add(this.label8);
            this.tpg_Page.Controls.Add(this.label7);
            this.tpg_Page.Controls.Add(this.label6);
            this.tpg_Page.Controls.Add(this.label3);
            this.tpg_Page.Controls.Add(this.groupBox3);
            this.tpg_Page.Controls.Add(this.groupBox2);
            this.tpg_Page.Controls.Add(this.label2);
            this.tpg_Page.Controls.Add(this.groupBox1);
            this.tpg_Page.Controls.Add(this.label1);
            this.tpg_Page.Controls.Add(this.panel1);
            this.tpg_Page.Controls.Add(this.panel2);
            this.tpg_Page.Location = new System.Drawing.Point(4, 0x18);
            this.tpg_Page.Name = "tpg_Page";
            this.tpg_Page.Size = new System.Drawing.Size(0x162, 230);
            this.tpg_Page.TabIndex = 0;
            this.tpg_Page.Text = "页面";
            this.rdb_Landscape.AutoSize = true;
            this.rdb_Landscape.Checked = true;
            this.rdb_Landscape.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.rdb_Landscape.Location = new System.Drawing.Point(0xc0, 0x1f);
            this.rdb_Landscape.Name = "rdb_Landscape";
            this.rdb_Landscape.Size = new System.Drawing.Size(0x41, 0x10);
            this.rdb_Landscape.TabIndex = 3;
            this.rdb_Landscape.TabStop = true;
            this.rdb_Landscape.Text = "横向(&L)";
            this.rdb_Landscape.Click += new System.EventHandler(this.rdb_Landscape_Click);
            this.pcb_OritationLandscape.Image = (System.Drawing.Image)resources.GetObject("pcb_OritationLandscape.Image");
            this.pcb_OritationLandscape.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.pcb_OritationLandscape.Location = new System.Drawing.Point(150, 0x1b);
            this.pcb_OritationLandscape.Name = "pcb_OritationLandscape";
            this.pcb_OritationLandscape.Size = new System.Drawing.Size(0x1f, 0x17);
            this.pcb_OritationLandscape.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pcb_OritationLandscape.TabIndex = 5;
            this.pcb_OritationLandscape.TabStop = false;
            this.pcb_OritationPortrait.Image = (System.Drawing.Image)resources.GetObject("pcb_OritationPortrait.Image");
            this.pcb_OritationPortrait.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.pcb_OritationPortrait.Location = new System.Drawing.Point(30, 0x19);
            this.pcb_OritationPortrait.Name = "pcb_OritationPortrait";
            this.pcb_OritationPortrait.Size = new System.Drawing.Size(0x19, 0x1f);
            this.pcb_OritationPortrait.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pcb_OritationPortrait.TabIndex = 4;
            this.pcb_OritationPortrait.TabStop = false;
            this.rdb_Portrait.AutoSize = true;
            this.rdb_Portrait.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.rdb_Portrait.Location = new System.Drawing.Point(0x42, 0x1f);
            this.rdb_Portrait.Name = "rdb_Portrait";
            this.rdb_Portrait.Size = new System.Drawing.Size(0x41, 0x10);
            this.rdb_Portrait.TabIndex = 2;
            this.rdb_Portrait.Text = "纵向(&T)";
            this.rdb_Portrait.Click += new System.EventHandler(this.rdb_Portrait_Click);
            this.txb_StartPage.Location = new System.Drawing.Point(0x60, 0xc7);
            this.txb_StartPage.Name = "txb_StartPage";
            this.txb_StartPage.Size = new System.Drawing.Size(0x36, 0x15);
            this.txb_StartPage.TabIndex = 0x16;
            this.txb_StartPage.Text = "自动";
            this.cbb_PaintQuality.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbb_PaintQuality.ItemHeight = 12;
            this.cbb_PaintQuality.Items.AddRange(new object[] { "1200 点/英寸", "600 点/英寸" });
            this.cbb_PaintQuality.Location = new System.Drawing.Point(0x60, 0xae);
            this.cbb_PaintQuality.Name = "cbb_PaintQuality";
            this.cbb_PaintQuality.Size = new System.Drawing.Size(0xde, 20);
            this.cbb_PaintQuality.TabIndex = 0x15;
            this.cbb_PaintQuality.SelectedIndex = 1;
            this.cbb_PageSize.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbb_PageSize.ItemHeight = 12;
            this.cbb_PageSize.Location = new System.Drawing.Point(0x60, 0x93);
            this.cbb_PageSize.Name = "cbb_PageSize";
            this.cbb_PageSize.Size = new System.Drawing.Size(0xde, 20);
            this.cbb_PageSize.TabIndex = 20;
            this.label8.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label8.Location = new System.Drawing.Point(6, 0xc7);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(0x52, 0x12);
            this.label8.TabIndex = 0x13;
            this.label8.Text = "起始页码(&R):";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label7.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label7.Location = new System.Drawing.Point(6, 0xae);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(0x52, 0x12);
            this.label7.TabIndex = 0x12;
            this.label7.Text = "打印质量(&Q):";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label6.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.label6.Location = new System.Drawing.Point(6, 0x93);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(0x52, 0x12);
            this.label6.TabIndex = 0x11;
            this.label6.Text = "纸张大小(&Z):";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label3.AutoSize = true;
            this.label3.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label3.Location = new System.Drawing.Point(0xcd, 0x55);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(0x41, 12);
            this.label3.TabIndex = 14;
            this.label3.Text = "% 正常尺寸";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.groupBox3.Location = new System.Drawing.Point(6, 0x83);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(0x144, 6);
            this.groupBox3.TabIndex = 8;
            this.groupBox3.TabStop = false;
            this.groupBox2.Location = new System.Drawing.Point(0x24, 0x3e);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(0x126, 6);
            this.groupBox2.TabIndex = 7;
            this.groupBox2.TabStop = false;
            this.label2.AutoSize = true;
            this.label2.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label2.Location = new System.Drawing.Point(6, 0x3e);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(0x1d, 12);
            this.label2.TabIndex = 6;
            this.label2.Text = "缩放";
            this.groupBox1.Location = new System.Drawing.Point(0x24, 6);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(0x126, 6);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.label1.AutoSize = true;
            this.label1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label1.Location = new System.Drawing.Point(5, 5);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(0x1d, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "方向";
            this.panel1.Location = new System.Drawing.Point(0x12, 0x13);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(0x108, 0x2b);
            this.panel1.TabIndex = 0x1a;
            this.panel2.Controls.Add(this.rdb_Zoom);
            this.panel2.Controls.Add(this.rdb_Adjust);
            this.panel2.Controls.Add(this.npd_PageHigh);
            this.panel2.Controls.Add(this.npd_PageWidth);
            this.panel2.Controls.Add(this.npd_Zoom);
            this.panel2.Controls.Add(this.label5);
            this.panel2.Controls.Add(this.label4);
            this.panel2.Location = new System.Drawing.Point(12, 80);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(0x13c, 0x30);
            this.panel2.TabIndex = 0x1b;
            this.rdb_Zoom.AutoSize = true;
            this.rdb_Zoom.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.rdb_Zoom.Location = new System.Drawing.Point(4, 3);
            this.rdb_Zoom.Name = "rdb_Zoom";
            this.rdb_Zoom.Size = new System.Drawing.Size(0x5f, 0x10);
            this.rdb_Zoom.TabIndex = 9;
            this.rdb_Zoom.Text = "缩放比例(&A):";
            this.rdb_Zoom.Click += new System.EventHandler(this.rdb_Zoom_Click);
            this.rdb_Adjust.Checked = true;
            this.rdb_Adjust.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.rdb_Adjust.Location = new System.Drawing.Point(4, 0x18);
            this.rdb_Adjust.Name = "rdb_Adjust";
            this.rdb_Adjust.Size = new System.Drawing.Size(0x58, 0x12);
            this.rdb_Adjust.TabIndex = 10;
            this.rdb_Adjust.TabStop = true;
            this.rdb_Adjust.Text = "调整为:(&F)";
            this.rdb_Adjust.Click += new System.EventHandler(this.rdb_Adjust_Click);
            this.npd_PageHigh.Location = new System.Drawing.Point(0xd0, 0x18);
            int[] bits = new int[4];
            bits[0] = 0x7fff;
            this.npd_PageHigh.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 1;
            this.npd_PageHigh.Minimum = new decimal(numArray2);
            this.npd_PageHigh.Name = "npd_PageHigh";
            this.npd_PageHigh.Size = new System.Drawing.Size(0x42, 0x15);
            this.npd_PageHigh.TabIndex = 0x19;
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.npd_PageHigh.Value = new decimal(numArray3);
            this.npd_PageHigh.ValueChanged += new System.EventHandler(this.npd_PageHigh_ValueChanged);
            this.npd_PageWidth.Location = new System.Drawing.Point(0x60, 0x18);
            int[] numArray4 = new int[4];
            numArray4[0] = 0x7fff;
            this.npd_PageWidth.Maximum = new decimal(numArray4);
            int[] numArray5 = new int[4];
            numArray5[0] = 1;
            this.npd_PageWidth.Minimum = new decimal(numArray5);
            this.npd_PageWidth.Name = "npd_PageWidth";
            this.npd_PageWidth.Size = new System.Drawing.Size(60, 0x15);
            this.npd_PageWidth.TabIndex = 0x18;
            int[] numArray6 = new int[4];
            numArray6[0] = 1;
            this.npd_PageWidth.Value = new decimal(numArray6);
            this.npd_PageWidth.ValueChanged += new System.EventHandler(this.npd_PageWidth_ValueChanged);
            int[] numArray7 = new int[4];
            numArray7[0] = 5;
            this.npd_Zoom.Increment = new decimal(numArray7);
            this.npd_Zoom.Location = new System.Drawing.Point(0x75, 0);
            int[] numArray8 = new int[4];
            numArray8[0] = 400;
            this.npd_Zoom.Maximum = new decimal(numArray8);
            int[] numArray9 = new int[4];
            numArray9[0] = 10;
            this.npd_Zoom.Minimum = new decimal(numArray9);
            this.npd_Zoom.Name = "npd_Zoom";
            this.npd_Zoom.Size = new System.Drawing.Size(60, 0x15);
            this.npd_Zoom.TabIndex = 0x17;
            int[] numArray10 = new int[4];
            numArray10[0] = 100;
            this.npd_Zoom.Value = new decimal(numArray10);
            this.npd_Zoom.ValueChanged += new System.EventHandler(this.npd_Zoom_ValueChanged);
            this.label5.AutoSize = true;
            this.label5.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label5.Location = new System.Drawing.Point(0x115, 0x1c);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(0x1d, 12);
            this.label5.TabIndex = 0x10;
            this.label5.Text = "页高";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label4.AutoSize = true;
            this.label4.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label4.Location = new System.Drawing.Point(0x9f, 0x1c);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(0x1d, 12);
            this.label4.TabIndex = 15;
            this.label4.Text = "页宽";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tpg_Margin.Controls.Add(this.pcb_Margin);
            this.tpg_Margin.Controls.Add(this.label15);
            this.tpg_Margin.Controls.Add(this.label14);
            this.tpg_Margin.Controls.Add(this.label13);
            this.tpg_Margin.Controls.Add(this.label12);
            this.tpg_Margin.Controls.Add(this.label11);
            this.tpg_Margin.Controls.Add(this.label10);
            this.tpg_Margin.Controls.Add(this.ckb_Vertical);
            this.tpg_Margin.Controls.Add(this.ckb_Level);
            this.tpg_Margin.Controls.Add(this.label9);
            this.tpg_Margin.Controls.Add(this.groupBox4);
            this.tpg_Margin.Controls.Add(this.npd_FooterMargin);
            this.tpg_Margin.Controls.Add(this.npd_HeaderMargin);
            this.tpg_Margin.Controls.Add(this.npd_RightMargin);
            this.tpg_Margin.Controls.Add(this.npd_LeftMargin);
            this.tpg_Margin.Controls.Add(this.npd_BottomMargin);
            this.tpg_Margin.Controls.Add(this.npd_TopMargin);
            this.tpg_Margin.Location = new System.Drawing.Point(4, 0x18);
            this.tpg_Margin.Name = "tpg_Margin";
            this.tpg_Margin.Size = new System.Drawing.Size(0x162, 230);
            this.tpg_Margin.TabIndex = 1;
            this.tpg_Margin.Text = "页边距";
            this.pcb_Margin.Image = (System.Drawing.Image)resources.GetObject("pcb_Margin.Image");
            this.pcb_Margin.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.pcb_Margin.Location = new System.Drawing.Point(0x66, 0x38);
            this.pcb_Margin.Name = "pcb_Margin";
            this.pcb_Margin.Size = new System.Drawing.Size(0x4b, 0x68);
            this.pcb_Margin.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pcb_Margin.TabIndex = 0x10;
            this.pcb_Margin.TabStop = false;
            this.label15.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label15.Location = new System.Drawing.Point(6, 0x51);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(0x24, 12);
            this.label15.TabIndex = 15;
            this.label15.Text = "左(&L):";
            this.label14.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label14.Location = new System.Drawing.Point(0x66, 0xa2);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(0x24, 12);
            this.label14.TabIndex = 14;
            this.label14.Text = "下(&B):";
            this.label13.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label13.Location = new System.Drawing.Point(210, 0x95);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(0x30, 13);
            this.label13.TabIndex = 13;
            this.label13.Text = "页脚(&F):";
            this.label12.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label12.Location = new System.Drawing.Point(210, 0x51);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(0x2a, 12);
            this.label12.TabIndex = 12;
            this.label12.Text = "右(&R):";
            this.label11.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label11.Location = new System.Drawing.Point(210, 6);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(0x30, 13);
            this.label11.TabIndex = 11;
            this.label11.Text = "页眉(&A):";
            this.label10.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label10.Location = new System.Drawing.Point(0x66, 5);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(0x24, 12);
            this.label10.TabIndex = 10;
            this.label10.Text = "上(&T):";
            this.ckb_Vertical.Checked = true;
            this.ckb_Vertical.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ckb_Vertical.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.ckb_Vertical.Location = new System.Drawing.Point(0x72, 0xcd);
            this.ckb_Vertical.Name = "ckb_Vertical";
            this.ckb_Vertical.Size = new System.Drawing.Size(0x4e, 0x13);
            this.ckb_Vertical.TabIndex = 9;
            this.ckb_Vertical.Text = "垂直(&V)";
            this.ckb_Vertical.Click += new System.EventHandler(this.ckb_Vertical_Click);
            this.ckb_Level.Checked = true;
            this.ckb_Level.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ckb_Level.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.ckb_Level.Location = new System.Drawing.Point(30, 0xcd);
            this.ckb_Level.Name = "ckb_Level";
            this.ckb_Level.Size = new System.Drawing.Size(0x52, 0x13);
            this.ckb_Level.TabIndex = 8;
            this.ckb_Level.Text = "水平(&Z)";
            this.ckb_Level.Click += new System.EventHandler(this.ckb_Level_Click);
            this.label9.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label9.Location = new System.Drawing.Point(6, 0xbc);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(0x36, 13);
            this.label9.TabIndex = 7;
            this.label9.Text = "居中方式";
            this.groupBox4.Location = new System.Drawing.Point(0x36, 0xc1);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(0x108, 6);
            this.groupBox4.TabIndex = 6;
            this.groupBox4.TabStop = false;
            this.npd_FooterMargin.DecimalPlaces = 1;
            int[] numArray11 = new int[4];
            numArray11[0] = 5;
            numArray11[3] = 0x10000;
            this.npd_FooterMargin.Increment = new decimal(numArray11);
            this.npd_FooterMargin.Location = new System.Drawing.Point(210, 0xae);
            this.npd_FooterMargin.Name = "npd_FooterMargin";
            this.npd_FooterMargin.Size = new System.Drawing.Size(0x36, 0x15);
            this.npd_FooterMargin.TabIndex = 5;
            this.npd_FooterMargin.Click += new System.EventHandler(this.npd_FooterMargin_Click);
            this.npd_HeaderMargin.DecimalPlaces = 1;
            int[] numArray12 = new int[4];
            numArray12[0] = 5;
            numArray12[3] = 0x10000;
            this.npd_HeaderMargin.Increment = new decimal(numArray12);
            this.npd_HeaderMargin.Location = new System.Drawing.Point(210, 0x13);
            this.npd_HeaderMargin.Name = "npd_HeaderMargin";
            this.npd_HeaderMargin.Size = new System.Drawing.Size(0x36, 0x15);
            this.npd_HeaderMargin.TabIndex = 4;
            this.npd_HeaderMargin.Click += new System.EventHandler(this.npd_HeaderMargin_Click);
            this.npd_RightMargin.DecimalPlaces = 1;
            int[] numArray13 = new int[4];
            numArray13[0] = 5;
            numArray13[3] = 0x10000;
            this.npd_RightMargin.Increment = new decimal(numArray13);
            this.npd_RightMargin.Location = new System.Drawing.Point(210, 0x5d);
            this.npd_RightMargin.Name = "npd_RightMargin";
            this.npd_RightMargin.Size = new System.Drawing.Size(0x36, 0x15);
            this.npd_RightMargin.TabIndex = 3;
            int[] numArray14 = new int[4];
            numArray14[0] = 5;
            numArray14[3] = 0x10000;
            this.npd_RightMargin.Value = new decimal(numArray14);
            this.npd_RightMargin.Click += new System.EventHandler(this.npd_RightMargin_Click);
            this.npd_LeftMargin.DecimalPlaces = 1;
            int[] numArray15 = new int[4];
            numArray15[0] = 5;
            numArray15[3] = 0x10000;
            this.npd_LeftMargin.Increment = new decimal(numArray15);
            this.npd_LeftMargin.Location = new System.Drawing.Point(6, 0x5d);
            this.npd_LeftMargin.Name = "npd_LeftMargin";
            this.npd_LeftMargin.Size = new System.Drawing.Size(0x30, 0x15);
            this.npd_LeftMargin.TabIndex = 2;
            int[] numArray16 = new int[4];
            numArray16[0] = 20;
            numArray16[3] = 0x10000;
            this.npd_LeftMargin.Value = new decimal(numArray16);
            this.npd_LeftMargin.Click += new System.EventHandler(this.npd_LeftMargin_Click);
            this.npd_BottomMargin.DecimalPlaces = 1;
            int[] numArray17 = new int[4];
            numArray17[0] = 5;
            numArray17[3] = 0x10000;
            this.npd_BottomMargin.Increment = new decimal(numArray17);
            this.npd_BottomMargin.Location = new System.Drawing.Point(0x66, 0xae);
            this.npd_BottomMargin.Name = "npd_BottomMargin";
            this.npd_BottomMargin.Size = new System.Drawing.Size(0x36, 0x15);
            this.npd_BottomMargin.TabIndex = 1;
            int[] numArray18 = new int[4];
            numArray18[0] = 5;
            numArray18[3] = 0x10000;
            this.npd_BottomMargin.Value = new decimal(numArray18);
            this.npd_BottomMargin.Click += new System.EventHandler(this.npd_BottomMargin_Click);
            this.npd_TopMargin.DecimalPlaces = 1;
            int[] numArray19 = new int[4];
            numArray19[0] = 5;
            numArray19[3] = 0x10000;
            this.npd_TopMargin.Increment = new decimal(numArray19);
            this.npd_TopMargin.Location = new System.Drawing.Point(0x66, 0x11);
            this.npd_TopMargin.Name = "npd_TopMargin";
            this.npd_TopMargin.Size = new System.Drawing.Size(0x36, 0x15);
            this.npd_TopMargin.TabIndex = 0;
            int[] numArray20 = new int[4];
            numArray20[0] = 5;
            numArray20[3] = 0x10000;
            this.npd_TopMargin.Value = new decimal(numArray20);
            this.npd_TopMargin.Click += new System.EventHandler(this.npd_TopMargin_Click);
            this.tpg_HeaderFooter.Controls.Add(this.label17);
            this.tpg_HeaderFooter.Controls.Add(this.label16);
            this.tpg_HeaderFooter.Controls.Add(this.txb_Footer);
            this.tpg_HeaderFooter.Controls.Add(this.cbb_Footer);
            this.tpg_HeaderFooter.Controls.Add(this.btn_CustomFooter);
            this.tpg_HeaderFooter.Controls.Add(this.btn_CustomHeader);
            this.tpg_HeaderFooter.Controls.Add(this.cbb_Header);
            this.tpg_HeaderFooter.Controls.Add(this.txb_Header);
            this.tpg_HeaderFooter.Location = new System.Drawing.Point(4, 0x18);
            this.tpg_HeaderFooter.Name = "tpg_HeaderFooter";
            this.tpg_HeaderFooter.Size = new System.Drawing.Size(0x162, 230);
            this.tpg_HeaderFooter.TabIndex = 2;
            this.tpg_HeaderFooter.Text = "页眉/页脚";
            this.label17.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label17.Location = new System.Drawing.Point(12, 0x83);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(0x30, 12);
            this.label17.TabIndex = 7;
            this.label17.Text = "页脚(&F):";
            this.label16.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label16.Location = new System.Drawing.Point(12, 0x38);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(0x30, 12);
            this.label16.TabIndex = 6;
            this.label16.Text = "页眉(&A):";
            this.txb_Footer.Location = new System.Drawing.Point(12, 0xae);
            this.txb_Footer.Multiline = true;
            this.txb_Footer.Name = "txb_Footer";
            this.txb_Footer.Size = new System.Drawing.Size(0x13e, 0x2c);
            this.txb_Footer.TabIndex = 5;
            this.cbb_Footer.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbb_Footer.ItemHeight = 12;
            this.cbb_Footer.Items.AddRange(new object[] { "(无)", "第 1 页", "第 1 页，共 ？页", "Sheet1", "Microsoft 机密，2003-10-31，第 1 页", "Book1", "Sheet1,第 1 页", "Sheet1,Microsoft 机密,第 1 页", "Book1,第 1 页", "第 1 页,Sheet1", "第 1 页,Book1" });
            this.cbb_Footer.Location = new System.Drawing.Point(12, 0x8f);
            this.cbb_Footer.Name = "cbb_Footer";
            this.cbb_Footer.Size = new System.Drawing.Size(0x13e, 20);
            this.cbb_Footer.TabIndex = 4;
            this.cbb_Footer.SelectedIndexChanged += new System.EventHandler(this.cbb_Footer_SelectedIndexChanged);
            this.btn_CustomFooter.Enabled = false;
            this.btn_CustomFooter.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.btn_CustomFooter.Location = new System.Drawing.Point(0xae, 100);
            this.btn_CustomFooter.Name = "btn_CustomFooter";
            this.btn_CustomFooter.Size = new System.Drawing.Size(150, 0x16);
            this.btn_CustomFooter.TabIndex = 3;
            this.btn_CustomFooter.Text = "自定义页脚(&U)...";
            this.btn_CustomHeader.Enabled = false;
            this.btn_CustomHeader.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.btn_CustomHeader.Location = new System.Drawing.Point(12, 100);
            this.btn_CustomHeader.Name = "btn_CustomHeader";
            this.btn_CustomHeader.Size = new System.Drawing.Size(0x90, 0x16);
            this.btn_CustomHeader.TabIndex = 2;
            this.btn_CustomHeader.Text = "自定义页眉(&C)...";
            this.cbb_Header.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbb_Header.ItemHeight = 12;
            this.cbb_Header.Items.AddRange(new object[] { "(无)", "第 1 页", "第 1 页，共 ？页", "Sheet1", "Microsoft 机密，2003-10-31，第 1 页", "Book1", "Sheet1,第 1 页", "Sheet1,Microsoft 机密,第 1 页", "Book1,第 1 页", "第 1 页,Sheet1", "第 1 页,Book1" });
            this.cbb_Header.Location = new System.Drawing.Point(12, 0x44);
            this.cbb_Header.Name = "cbb_Header";
            this.cbb_Header.Size = new System.Drawing.Size(0x13e, 20);
            this.cbb_Header.TabIndex = 1;
            this.cbb_Header.SelectedIndexChanged += new System.EventHandler(this.cbb_Header_SelectedIndexChanged);
            this.txb_Header.Location = new System.Drawing.Point(12, 6);
            this.txb_Header.Multiline = true;
            this.txb_Header.Name = "txb_Header";
            this.txb_Header.Size = new System.Drawing.Size(0x13e, 0x2c);
            this.txb_Header.TabIndex = 0;
            this.tpg_Table.Controls.Add(this.chk_ShrinkToFit);
            this.tpg_Table.Controls.Add(this.cbb_PrintWrongCell);
            this.tpg_Table.Controls.Add(this.cbb_Postil);
            this.tpg_Table.Controls.Add(this.pcb_PrintOrder);
            this.tpg_Table.Controls.Add(this.rdb_RowFirst);
            this.tpg_Table.Controls.Add(this.rdb_ListFirst);
            this.tpg_Table.Controls.Add(this.label24);
            this.tpg_Table.Controls.Add(this.label23);
            this.tpg_Table.Controls.Add(this.ckb_RowList);
            this.tpg_Table.Controls.Add(this.ckb_PrintAsDraft);
            this.tpg_Table.Controls.Add(this.ckb_SingleColor);
            this.tpg_Table.Controls.Add(this.ckb_GridLine);
            this.tpg_Table.Controls.Add(this.label20);
            this.tpg_Table.Controls.Add(this.label19);
            this.tpg_Table.Controls.Add(this.groupBox7);
            this.tpg_Table.Controls.Add(this.groupBox6);
            this.tpg_Table.Controls.Add(this.panel3);
            this.tpg_Table.Location = new System.Drawing.Point(4, 0x18);
            this.tpg_Table.Name = "tpg_Table";
            this.tpg_Table.Size = new System.Drawing.Size(0x162, 230);
            this.tpg_Table.TabIndex = 3;
            this.tpg_Table.Text = "工作表";
            this.chk_ShrinkToFit.AutoSize = true;
            this.chk_ShrinkToFit.Checked = true;
            this.chk_ShrinkToFit.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chk_ShrinkToFit.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.chk_ShrinkToFit.Location = new System.Drawing.Point(0x12, 0x69);
            this.chk_ShrinkToFit.Name = "chk_ShrinkToFit";
            this.chk_ShrinkToFit.Size = new System.Drawing.Size(0x84, 0x10);
            this.chk_ShrinkToFit.TabIndex = 20;
            this.chk_ShrinkToFit.Text = "输出时缩小字体填充";
            this.cbb_PrintWrongCell.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbb_PrintWrongCell.ItemHeight = 12;
            this.cbb_PrintWrongCell.Items.AddRange(new object[] { "显示值", "<空白>", "--", "#N/A" });
            this.cbb_PrintWrongCell.Location = new System.Drawing.Point(0x108, 0x4b);
            this.cbb_PrintWrongCell.Name = "cbb_PrintWrongCell";
            this.cbb_PrintWrongCell.Size = new System.Drawing.Size(0x4e, 20);
            this.cbb_PrintWrongCell.TabIndex = 13;
            this.cbb_Postil.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbb_Postil.ItemHeight = 12;
            this.cbb_Postil.Items.AddRange(new object[] { "(无)", "工作表末尾", "如同工作表中的显示" });
            this.cbb_Postil.Location = new System.Drawing.Point(200, 0x31);
            this.cbb_Postil.Name = "cbb_Postil";
            this.cbb_Postil.Size = new System.Drawing.Size(0x90, 20);
            this.cbb_Postil.TabIndex = 12;
            this.pcb_PrintOrder.Image = (System.Drawing.Image)resources.GetObject("pcb_PrintOrder.Image");
            this.pcb_PrintOrder.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.pcb_PrintOrder.Location = new System.Drawing.Point(0xba, 0xa2);
            this.pcb_PrintOrder.Name = "pcb_PrintOrder";
            this.pcb_PrintOrder.Size = new System.Drawing.Size(0x4a, 0x2f);
            this.pcb_PrintOrder.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pcb_PrintOrder.TabIndex = 0x12;
            this.pcb_PrintOrder.TabStop = false;
            this.rdb_RowFirst.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.rdb_RowFirst.Location = new System.Drawing.Point(0x18, 0xc1);
            this.rdb_RowFirst.Name = "rdb_RowFirst";
            this.rdb_RowFirst.Size = new System.Drawing.Size(0x60, 0x13);
            this.rdb_RowFirst.TabIndex = 0x11;
            this.rdb_RowFirst.Text = "先行后列(&V)";
            this.rdb_RowFirst.Click += new System.EventHandler(this.rdb_RowFirst_Click);
            this.rdb_RowFirst.Checked = true;
            this.rdb_ListFirst.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.rdb_ListFirst.Location = new System.Drawing.Point(0x18, 0x9c);
            this.rdb_ListFirst.Name = "rdb_ListFirst";
            this.rdb_ListFirst.Size = new System.Drawing.Size(0x60, 0x12);
            this.rdb_ListFirst.TabIndex = 0x10;
            this.rdb_ListFirst.Text = "先列后行(&D)";
            this.rdb_ListFirst.Click += new System.EventHandler(this.rdb_ListFirst_Click);
            this.label24.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label24.Location = new System.Drawing.Point(130, 80);
            this.label24.Name = "label24";
            this.label24.Size = new System.Drawing.Size(130, 13);
            this.label24.TabIndex = 15;
            this.label24.Text = "错误单元格打印为(&E):";
            this.label23.AutoSize = true;
            this.label23.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label23.Location = new System.Drawing.Point(130, 0x35);
            this.label23.Name = "label23";
            this.label23.Size = new System.Drawing.Size(0x3b, 12);
            this.label23.TabIndex = 14;
            this.label23.Text = "批注(&M)：";
            this.ckb_RowList.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.ckb_RowList.Location = new System.Drawing.Point(130, 0x1a);
            this.ckb_RowList.Name = "ckb_RowList";
            this.ckb_RowList.Size = new System.Drawing.Size(0x66, 0x13);
            this.ckb_RowList.TabIndex = 11;
            this.ckb_RowList.Text = "行号列标(&L)";
            this.ckb_PrintAsDraft.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.ckb_PrintAsDraft.Location = new System.Drawing.Point(0x12, 0x4e);
            this.ckb_PrintAsDraft.Name = "ckb_PrintAsDraft";
            this.ckb_PrintAsDraft.Size = new System.Drawing.Size(110, 0x13);
            this.ckb_PrintAsDraft.TabIndex = 10;
            this.ckb_PrintAsDraft.Text = "按草稿方式(&Q)";
            this.ckb_SingleColor.AutoSize = true;
            this.ckb_SingleColor.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.ckb_SingleColor.Location = new System.Drawing.Point(0x12, 0x34);
            this.ckb_SingleColor.Name = "ckb_SingleColor";
            this.ckb_SingleColor.Size = new System.Drawing.Size(90, 0x10);
            this.ckb_SingleColor.TabIndex = 9;
            this.ckb_SingleColor.Text = "单色打印(&B)";
            this.ckb_GridLine.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.ckb_GridLine.Location = new System.Drawing.Point(0x12, 0x1a);
            this.ckb_GridLine.Name = "ckb_GridLine";
            this.ckb_GridLine.Size = new System.Drawing.Size(0x56, 0x13);
            this.ckb_GridLine.TabIndex = 8;
            this.ckb_GridLine.Text = "网格线(&G)";
            this.label20.AutoSize = true;
            this.label20.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label20.Location = new System.Drawing.Point(6, 0x83);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(0x35, 12);
            this.label20.TabIndex = 5;
            this.label20.Text = "打印顺序";
            this.label19.AutoSize = true;
            this.label19.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.label19.Location = new System.Drawing.Point(6, 6);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(0x1d, 12);
            this.label19.TabIndex = 4;
            this.label19.Text = "打印";
            this.groupBox7.Location = new System.Drawing.Point(0x36, 0x83);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(270, 6);
            this.groupBox7.TabIndex = 2;
            this.groupBox7.TabStop = false;
            this.groupBox6.Location = new System.Drawing.Point(30, 6);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new System.Drawing.Size(0x126, 6);
            this.groupBox6.TabIndex = 1;
            this.groupBox6.TabStop = false;
            this.panel3.Location = new System.Drawing.Point(0x12, 0x95);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(0x76, 0x45);
            this.panel3.TabIndex = 0x13;
            this.btn_Ensure.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.btn_Ensure.Location = new System.Drawing.Point(0xba, 0x110);
            this.btn_Ensure.Name = "btn_Ensure";
            this.btn_Ensure.Size = new System.Drawing.Size(0x42, 0x16);
            this.btn_Ensure.TabIndex = 1;
            this.btn_Ensure.Text = "确定";
            this.btn_Ensure.Click += new System.EventHandler(this.btn_Ensure_Click);
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Cancel.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.btn_Cancel.Location = new System.Drawing.Point(0x114, 0x110);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.Size = new System.Drawing.Size(0x42, 0x16);
            this.btn_Cancel.TabIndex = 2;
            this.btn_Cancel.Text = "取消";
            base.AcceptButton = this.btn_Ensure;
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 14);
            base.CancelButton = this.btn_Cancel;
            base.ClientSize = new System.Drawing.Size(0x17a, 0x12e);
            base.Controls.Add(this.btn_Cancel);
            base.Controls.Add(this.btn_Ensure);
            base.Controls.Add(this.tcl_PageSetting);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "DlgPageSetup";
            base.ShowInTaskbar = false;
            base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "页面设置";
            base.TopMost = true;
            this.tcl_PageSetting.ResumeLayout(false);
            this.tpg_Page.ResumeLayout(false);
            this.tpg_Page.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)this.pcb_OritationLandscape).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.pcb_OritationPortrait).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.npd_PageHigh.EndInit();
            this.npd_PageWidth.EndInit();
            this.npd_Zoom.EndInit();
            this.tpg_Margin.ResumeLayout(false);
            this.tpg_Margin.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)this.pcb_Margin).EndInit();
            this.npd_FooterMargin.EndInit();
            this.npd_HeaderMargin.EndInit();
            this.npd_RightMargin.EndInit();
            this.npd_LeftMargin.EndInit();
            this.npd_BottomMargin.EndInit();
            this.npd_TopMargin.EndInit();
            this.tpg_HeaderFooter.ResumeLayout(false);
            this.tpg_HeaderFooter.PerformLayout();
            this.tpg_Table.ResumeLayout(false);
            this.tpg_Table.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)this.pcb_PrintOrder).EndInit();
            base.ResumeLayout(false);
        }
        #endregion 
        private System.Windows.Forms.Button btn_Cancel;
        private System.Windows.Forms.Button btn_CustomFooter;
        private System.Windows.Forms.Button btn_CustomHeader;
        private System.Windows.Forms.Button btn_Ensure;
        private System.Windows.Forms.ComboBox cbb_Footer;
        private System.Windows.Forms.ComboBox cbb_Header;
        private System.Windows.Forms.ComboBox cbb_PageSize;
        private System.Windows.Forms.ComboBox cbb_PaintQuality;
        private System.Windows.Forms.ComboBox cbb_Postil;
        private System.Windows.Forms.ComboBox cbb_PrintWrongCell;
        private System.Windows.Forms.CheckBox chk_ShrinkToFit;
        private System.Windows.Forms.CheckBox ckb_GridLine;
        private System.Windows.Forms.CheckBox ckb_Level;
        private System.Windows.Forms.CheckBox ckb_PrintAsDraft;
        private System.Windows.Forms.CheckBox ckb_RowList;
        private System.Windows.Forms.CheckBox ckb_SingleColor;
        private System.Windows.Forms.CheckBox ckb_Vertical;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.GroupBox groupBox7;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.NumericUpDown npd_BottomMargin;
        private System.Windows.Forms.NumericUpDown npd_FooterMargin;
        private System.Windows.Forms.NumericUpDown npd_HeaderMargin;
        private System.Windows.Forms.NumericUpDown npd_LeftMargin;
        private System.Windows.Forms.NumericUpDown npd_PageHigh;
        private System.Windows.Forms.NumericUpDown npd_PageWidth;
        private System.Windows.Forms.NumericUpDown npd_RightMargin;
        private System.Windows.Forms.NumericUpDown npd_TopMargin;
        private System.Windows.Forms.NumericUpDown npd_Zoom;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.PictureBox pcb_Margin;
        private System.Windows.Forms.PictureBox pcb_OritationLandscape;
        private System.Windows.Forms.PictureBox pcb_OritationPortrait;
        private System.Windows.Forms.PictureBox pcb_PrintOrder;
        private System.Windows.Forms.RadioButton rdb_Adjust;
        private System.Windows.Forms.RadioButton rdb_Landscape;
        private System.Windows.Forms.RadioButton rdb_ListFirst;
        private System.Windows.Forms.RadioButton rdb_Portrait;
        private System.Windows.Forms.RadioButton rdb_RowFirst;
        private System.Windows.Forms.RadioButton rdb_Zoom;
        private System.Windows.Forms.TabControl tcl_PageSetting;
        private System.Windows.Forms.TabPage tpg_HeaderFooter;
        private System.Windows.Forms.TabPage tpg_Margin;
        private System.Windows.Forms.TabPage tpg_Page;
        private System.Windows.Forms.TabPage tpg_Table;
        private System.Windows.Forms.TextBox txb_Footer;
        private System.Windows.Forms.TextBox txb_Header;
        private System.Windows.Forms.TextBox txb_StartPage;
    }
}