namespace Thyt.TiPLM.UIL.PPM.PPCardModeling {
    partial class DlgPicture {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary> 
        ///      

        private void InitializeComponent() {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(DlgPicture));
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnOk = new System.Windows.Forms.Button();
            this.panel1 = new System.Windows.Forms.Panel();
            this.chkGrayscale = new System.Windows.Forms.CheckBox();
            this.txtCellEnd = new System.Windows.Forms.TextBox();
            this.txtCellStart = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.numFileIndex = new System.Windows.Forms.NumericUpDown();
            this.label1 = new System.Windows.Forms.Label();
            this.cmbPicType = new System.Windows.Forms.ComboBox();
            this.panel1.SuspendLayout();
            this.numFileIndex.BeginInit();
            base.SuspendLayout();
            this.btnCancel.AccessibleDescription = resources.GetString("btnCancel.AccessibleDescription");
            this.btnCancel.AccessibleName = resources.GetString("btnCancel.AccessibleName");
            this.btnCancel.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("btnCancel.Anchor");
            this.btnCancel.BackgroundImage = (System.Drawing.Image)resources.GetObject("btnCancel.BackgroundImage");
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("btnCancel.Dock");
            this.btnCancel.Enabled = (bool)resources.GetObject("btnCancel.Enabled");
            this.btnCancel.FlatStyle = (System.Windows.Forms.FlatStyle)resources.GetObject("btnCancel.FlatStyle");
            this.btnCancel.Font = (System.Drawing.Font)resources.GetObject("btnCancel.Font");
            this.btnCancel.Image = (System.Drawing.Image)resources.GetObject("btnCancel.Image");
            this.btnCancel.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("btnCancel.ImageAlign");
            this.btnCancel.ImageIndex = (int)resources.GetObject("btnCancel.ImageIndex");
            this.btnCancel.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("btnCancel.ImeMode");
            this.btnCancel.Location = (System.Drawing.Point)resources.GetObject("btnCancel.Location");
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("btnCancel.RightToLeft");
            this.btnCancel.Size = (System.Drawing.Size)resources.GetObject("btnCancel.Size");
            this.btnCancel.TabIndex = (int)resources.GetObject("btnCancel.TabIndex");
            this.btnCancel.Text = resources.GetString("btnCancel.Text");
            this.btnCancel.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("btnCancel.TextAlign");
            this.btnCancel.Visible = (bool)resources.GetObject("btnCancel.Visible");
            this.btnOk.AccessibleDescription = resources.GetString("btnOk.AccessibleDescription");
            this.btnOk.AccessibleName = resources.GetString("btnOk.AccessibleName");
            this.btnOk.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("btnOk.Anchor");
            this.btnOk.BackgroundImage = (System.Drawing.Image)resources.GetObject("btnOk.BackgroundImage");
            this.btnOk.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("btnOk.Dock");
            this.btnOk.Enabled = (bool)resources.GetObject("btnOk.Enabled");
            this.btnOk.FlatStyle = (System.Windows.Forms.FlatStyle)resources.GetObject("btnOk.FlatStyle");
            this.btnOk.Font = (System.Drawing.Font)resources.GetObject("btnOk.Font");
            this.btnOk.Image = (System.Drawing.Image)resources.GetObject("btnOk.Image");
            this.btnOk.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("btnOk.ImageAlign");
            this.btnOk.ImageIndex = (int)resources.GetObject("btnOk.ImageIndex");
            this.btnOk.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("btnOk.ImeMode");
            this.btnOk.Location = (System.Drawing.Point)resources.GetObject("btnOk.Location");
            this.btnOk.Name = "btnOk";
            this.btnOk.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("btnOk.RightToLeft");
            this.btnOk.Size = (System.Drawing.Size)resources.GetObject("btnOk.Size");
            this.btnOk.TabIndex = (int)resources.GetObject("btnOk.TabIndex");
            this.btnOk.Text = resources.GetString("btnOk.Text");
            this.btnOk.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("btnOk.TextAlign");
            this.btnOk.Visible = (bool)resources.GetObject("btnOk.Visible");
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.panel1.AccessibleDescription = resources.GetString("panel1.AccessibleDescription");
            this.panel1.AccessibleName = resources.GetString("panel1.AccessibleName");
            this.panel1.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("panel1.Anchor");
            this.panel1.AutoScroll = (bool)resources.GetObject("panel1.AutoScroll");
            this.panel1.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("panel1.AutoScrollMargin");
            this.panel1.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("panel1.AutoScrollMinSize");
            this.panel1.BackgroundImage = (System.Drawing.Image)resources.GetObject("panel1.BackgroundImage");
            this.panel1.Controls.Add(this.chkGrayscale);
            this.panel1.Controls.Add(this.txtCellEnd);
            this.panel1.Controls.Add(this.txtCellStart);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.numFileIndex);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.cmbPicType);
            this.panel1.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("panel1.Dock");
            this.panel1.Enabled = (bool)resources.GetObject("panel1.Enabled");
            this.panel1.Font = (System.Drawing.Font)resources.GetObject("panel1.Font");
            this.panel1.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("panel1.ImeMode");
            this.panel1.Location = (System.Drawing.Point)resources.GetObject("panel1.Location");
            this.panel1.Name = "panel1";
            this.panel1.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("panel1.RightToLeft");
            this.panel1.Size = (System.Drawing.Size)resources.GetObject("panel1.Size");
            this.panel1.TabIndex = (int)resources.GetObject("panel1.TabIndex");
            this.panel1.Text = resources.GetString("panel1.Text");
            this.panel1.Visible = (bool)resources.GetObject("panel1.Visible");
            this.chkGrayscale.AccessibleDescription = resources.GetString("chkGrayscale.AccessibleDescription");
            this.chkGrayscale.AccessibleName = resources.GetString("chkGrayscale.AccessibleName");
            this.chkGrayscale.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("chkGrayscale.Anchor");
            this.chkGrayscale.Appearance = (System.Windows.Forms.Appearance)resources.GetObject("chkGrayscale.Appearance");
            this.chkGrayscale.BackgroundImage = (System.Drawing.Image)resources.GetObject("chkGrayscale.BackgroundImage");
            this.chkGrayscale.CheckAlign = (System.Drawing.ContentAlignment)resources.GetObject("chkGrayscale.CheckAlign");
            this.chkGrayscale.Checked = true;
            this.chkGrayscale.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkGrayscale.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("chkGrayscale.Dock");
            this.chkGrayscale.Enabled = (bool)resources.GetObject("chkGrayscale.Enabled");
            this.chkGrayscale.FlatStyle = (System.Windows.Forms.FlatStyle)resources.GetObject("chkGrayscale.FlatStyle");
            this.chkGrayscale.Font = (System.Drawing.Font)resources.GetObject("chkGrayscale.Font");
            this.chkGrayscale.Image = (System.Drawing.Image)resources.GetObject("chkGrayscale.Image");
            this.chkGrayscale.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("chkGrayscale.ImageAlign");
            this.chkGrayscale.ImageIndex = (int)resources.GetObject("chkGrayscale.ImageIndex");
            this.chkGrayscale.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("chkGrayscale.ImeMode");
            this.chkGrayscale.Location = (System.Drawing.Point)resources.GetObject("chkGrayscale.Location");
            this.chkGrayscale.Name = "chkGrayscale";
            this.chkGrayscale.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("chkGrayscale.RightToLeft");
            this.chkGrayscale.Size = (System.Drawing.Size)resources.GetObject("chkGrayscale.Size");
            this.chkGrayscale.TabIndex = (int)resources.GetObject("chkGrayscale.TabIndex");
            this.chkGrayscale.Text = resources.GetString("chkGrayscale.Text");
            this.chkGrayscale.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("chkGrayscale.TextAlign");
            this.chkGrayscale.Visible = (bool)resources.GetObject("chkGrayscale.Visible");
            this.txtCellEnd.AccessibleDescription = resources.GetString("txtCellEnd.AccessibleDescription");
            this.txtCellEnd.AccessibleName = resources.GetString("txtCellEnd.AccessibleName");
            this.txtCellEnd.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("txtCellEnd.Anchor");
            this.txtCellEnd.AutoSize = (bool)resources.GetObject("txtCellEnd.AutoSize");
            this.txtCellEnd.BackgroundImage = (System.Drawing.Image)resources.GetObject("txtCellEnd.BackgroundImage");
            this.txtCellEnd.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("txtCellEnd.Dock");
            this.txtCellEnd.Enabled = (bool)resources.GetObject("txtCellEnd.Enabled");
            this.txtCellEnd.Font = (System.Drawing.Font)resources.GetObject("txtCellEnd.Font");
            this.txtCellEnd.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("txtCellEnd.ImeMode");
            this.txtCellEnd.Location = (System.Drawing.Point)resources.GetObject("txtCellEnd.Location");
            this.txtCellEnd.MaxLength = (int)resources.GetObject("txtCellEnd.MaxLength");
            this.txtCellEnd.Multiline = (bool)resources.GetObject("txtCellEnd.Multiline");
            this.txtCellEnd.Name = "txtCellEnd";
            this.txtCellEnd.PasswordChar = (char)resources.GetObject("txtCellEnd.PasswordChar");
            this.txtCellEnd.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("txtCellEnd.RightToLeft");
            this.txtCellEnd.ScrollBars = (System.Windows.Forms.ScrollBars)resources.GetObject("txtCellEnd.ScrollBars");
            this.txtCellEnd.Size = (System.Drawing.Size)resources.GetObject("txtCellEnd.Size");
            this.txtCellEnd.TabIndex = (int)resources.GetObject("txtCellEnd.TabIndex");
            this.txtCellEnd.Text = resources.GetString("txtCellEnd.Text");
            this.txtCellEnd.TextAlign = (System.Windows.Forms.HorizontalAlignment)resources.GetObject("txtCellEnd.TextAlign");
            this.txtCellEnd.Visible = (bool)resources.GetObject("txtCellEnd.Visible");
            this.txtCellEnd.WordWrap = (bool)resources.GetObject("txtCellEnd.WordWrap");
            this.txtCellStart.AccessibleDescription = resources.GetString("txtCellStart.AccessibleDescription");
            this.txtCellStart.AccessibleName = resources.GetString("txtCellStart.AccessibleName");
            this.txtCellStart.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("txtCellStart.Anchor");
            this.txtCellStart.AutoSize = (bool)resources.GetObject("txtCellStart.AutoSize");
            this.txtCellStart.BackgroundImage = (System.Drawing.Image)resources.GetObject("txtCellStart.BackgroundImage");
            this.txtCellStart.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("txtCellStart.Dock");
            this.txtCellStart.Enabled = (bool)resources.GetObject("txtCellStart.Enabled");
            this.txtCellStart.Font = (System.Drawing.Font)resources.GetObject("txtCellStart.Font");
            this.txtCellStart.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("txtCellStart.ImeMode");
            this.txtCellStart.Location = (System.Drawing.Point)resources.GetObject("txtCellStart.Location");
            this.txtCellStart.MaxLength = (int)resources.GetObject("txtCellStart.MaxLength");
            this.txtCellStart.Multiline = (bool)resources.GetObject("txtCellStart.Multiline");
            this.txtCellStart.Name = "txtCellStart";
            this.txtCellStart.PasswordChar = (char)resources.GetObject("txtCellStart.PasswordChar");
            this.txtCellStart.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("txtCellStart.RightToLeft");
            this.txtCellStart.ScrollBars = (System.Windows.Forms.ScrollBars)resources.GetObject("txtCellStart.ScrollBars");
            this.txtCellStart.Size = (System.Drawing.Size)resources.GetObject("txtCellStart.Size");
            this.txtCellStart.TabIndex = (int)resources.GetObject("txtCellStart.TabIndex");
            this.txtCellStart.Text = resources.GetString("txtCellStart.Text");
            this.txtCellStart.TextAlign = (System.Windows.Forms.HorizontalAlignment)resources.GetObject("txtCellStart.TextAlign");
            this.txtCellStart.Visible = (bool)resources.GetObject("txtCellStart.Visible");
            this.txtCellStart.WordWrap = (bool)resources.GetObject("txtCellStart.WordWrap");
            this.label4.AccessibleDescription = resources.GetString("label4.AccessibleDescription");
            this.label4.AccessibleName = resources.GetString("label4.AccessibleName");
            this.label4.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("label4.Anchor");
            this.label4.AutoSize = (bool)resources.GetObject("label4.AutoSize");
            this.label4.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("label4.Dock");
            this.label4.Enabled = (bool)resources.GetObject("label4.Enabled");
            this.label4.Font = (System.Drawing.Font)resources.GetObject("label4.Font");
            this.label4.Image = (System.Drawing.Image)resources.GetObject("label4.Image");
            this.label4.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("label4.ImageAlign");
            this.label4.ImageIndex = (int)resources.GetObject("label4.ImageIndex");
            this.label4.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("label4.ImeMode");
            this.label4.Location = (System.Drawing.Point)resources.GetObject("label4.Location");
            this.label4.Name = "label4";
            this.label4.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("label4.RightToLeft");
            this.label4.Size = (System.Drawing.Size)resources.GetObject("label4.Size");
            this.label4.TabIndex = (int)resources.GetObject("label4.TabIndex");
            this.label4.Text = resources.GetString("label4.Text");
            this.label4.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("label4.TextAlign");
            this.label4.Visible = (bool)resources.GetObject("label4.Visible");
            this.label3.AccessibleDescription = resources.GetString("label3.AccessibleDescription");
            this.label3.AccessibleName = resources.GetString("label3.AccessibleName");
            this.label3.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("label3.Anchor");
            this.label3.AutoSize = (bool)resources.GetObject("label3.AutoSize");
            this.label3.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("label3.Dock");
            this.label3.Enabled = (bool)resources.GetObject("label3.Enabled");
            this.label3.Font = (System.Drawing.Font)resources.GetObject("label3.Font");
            this.label3.Image = (System.Drawing.Image)resources.GetObject("label3.Image");
            this.label3.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("label3.ImageAlign");
            this.label3.ImageIndex = (int)resources.GetObject("label3.ImageIndex");
            this.label3.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("label3.ImeMode");
            this.label3.Location = (System.Drawing.Point)resources.GetObject("label3.Location");
            this.label3.Name = "label3";
            this.label3.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("label3.RightToLeft");
            this.label3.Size = (System.Drawing.Size)resources.GetObject("label3.Size");
            this.label3.TabIndex = (int)resources.GetObject("label3.TabIndex");
            this.label3.Text = resources.GetString("label3.Text");
            this.label3.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("label3.TextAlign");
            this.label3.Visible = (bool)resources.GetObject("label3.Visible");
            this.label2.AccessibleDescription = resources.GetString("label2.AccessibleDescription");
            this.label2.AccessibleName = resources.GetString("label2.AccessibleName");
            this.label2.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("label2.Anchor");
            this.label2.AutoSize = (bool)resources.GetObject("label2.AutoSize");
            this.label2.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("label2.Dock");
            this.label2.Enabled = (bool)resources.GetObject("label2.Enabled");
            this.label2.Font = (System.Drawing.Font)resources.GetObject("label2.Font");
            this.label2.Image = (System.Drawing.Image)resources.GetObject("label2.Image");
            this.label2.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("label2.ImageAlign");
            this.label2.ImageIndex = (int)resources.GetObject("label2.ImageIndex");
            this.label2.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("label2.ImeMode");
            this.label2.Location = (System.Drawing.Point)resources.GetObject("label2.Location");
            this.label2.Name = "label2";
            this.label2.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("label2.RightToLeft");
            this.label2.Size = (System.Drawing.Size)resources.GetObject("label2.Size");
            this.label2.TabIndex = (int)resources.GetObject("label2.TabIndex");
            this.label2.Text = resources.GetString("label2.Text");
            this.label2.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("label2.TextAlign");
            this.label2.Visible = (bool)resources.GetObject("label2.Visible");
            this.numFileIndex.AccessibleDescription = resources.GetString("numFileIndex.AccessibleDescription");
            this.numFileIndex.AccessibleName = resources.GetString("numFileIndex.AccessibleName");
            this.numFileIndex.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("numFileIndex.Anchor");
            this.numFileIndex.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("numFileIndex.Dock");
            this.numFileIndex.Enabled = (bool)resources.GetObject("numFileIndex.Enabled");
            this.numFileIndex.Font = (System.Drawing.Font)resources.GetObject("numFileIndex.Font");
            this.numFileIndex.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("numFileIndex.ImeMode");
            this.numFileIndex.Location = (System.Drawing.Point)resources.GetObject("numFileIndex.Location");
            int[] bits = new int[4];
            bits[0] = 10;
            this.numFileIndex.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 1;
            this.numFileIndex.Minimum = new decimal(numArray2);
            this.numFileIndex.Name = "numFileIndex";
            this.numFileIndex.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("numFileIndex.RightToLeft");
            this.numFileIndex.Size = (System.Drawing.Size)resources.GetObject("numFileIndex.Size");
            this.numFileIndex.TabIndex = (int)resources.GetObject("numFileIndex.TabIndex");
            this.numFileIndex.TextAlign = (System.Windows.Forms.HorizontalAlignment)resources.GetObject("numFileIndex.TextAlign");
            this.numFileIndex.ThousandsSeparator = (bool)resources.GetObject("numFileIndex.ThousandsSeparator");
            this.numFileIndex.UpDownAlign = (System.Windows.Forms.LeftRightAlignment)resources.GetObject("numFileIndex.UpDownAlign");
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.numFileIndex.Value = new decimal(numArray3);
            this.numFileIndex.Visible = (bool)resources.GetObject("numFileIndex.Visible");
            this.label1.AccessibleDescription = resources.GetString("label1.AccessibleDescription");
            this.label1.AccessibleName = resources.GetString("label1.AccessibleName");
            this.label1.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("label1.Anchor");
            this.label1.AutoSize = (bool)resources.GetObject("label1.AutoSize");
            this.label1.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("label1.Dock");
            this.label1.Enabled = (bool)resources.GetObject("label1.Enabled");
            this.label1.Font = (System.Drawing.Font)resources.GetObject("label1.Font");
            this.label1.Image = (System.Drawing.Image)resources.GetObject("label1.Image");
            this.label1.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("label1.ImageAlign");
            this.label1.ImageIndex = (int)resources.GetObject("label1.ImageIndex");
            this.label1.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("label1.ImeMode");
            this.label1.Location = (System.Drawing.Point)resources.GetObject("label1.Location");
            this.label1.Name = "label1";
            this.label1.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("label1.RightToLeft");
            this.label1.Size = (System.Drawing.Size)resources.GetObject("label1.Size");
            this.label1.TabIndex = (int)resources.GetObject("label1.TabIndex");
            this.label1.Text = resources.GetString("label1.Text");
            this.label1.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("label1.TextAlign");
            this.label1.Visible = (bool)resources.GetObject("label1.Visible");
            this.cmbPicType.AccessibleDescription = resources.GetString("cmbPicType.AccessibleDescription");
            this.cmbPicType.AccessibleName = resources.GetString("cmbPicType.AccessibleName");
            this.cmbPicType.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("cmbPicType.Anchor");
            this.cmbPicType.BackgroundImage = (System.Drawing.Image)resources.GetObject("cmbPicType.BackgroundImage");
            this.cmbPicType.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("cmbPicType.Dock");
            this.cmbPicType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPicType.Enabled = (bool)resources.GetObject("cmbPicType.Enabled");
            this.cmbPicType.Font = (System.Drawing.Font)resources.GetObject("cmbPicType.Font");
            this.cmbPicType.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("cmbPicType.ImeMode");
            this.cmbPicType.IntegralHeight = (bool)resources.GetObject("cmbPicType.IntegralHeight");
            this.cmbPicType.ItemHeight = (int)resources.GetObject("cmbPicType.ItemHeight");
            this.cmbPicType.Location = (System.Drawing.Point)resources.GetObject("cmbPicType.Location");
            this.cmbPicType.MaxDropDownItems = (int)resources.GetObject("cmbPicType.MaxDropDownItems");
            this.cmbPicType.MaxLength = (int)resources.GetObject("cmbPicType.MaxLength");
            this.cmbPicType.Name = "cmbPicType";
            this.cmbPicType.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("cmbPicType.RightToLeft");
            this.cmbPicType.Size = (System.Drawing.Size)resources.GetObject("cmbPicType.Size");
            this.cmbPicType.TabIndex = (int)resources.GetObject("cmbPicType.TabIndex");
            this.cmbPicType.Text = resources.GetString("cmbPicType.Text");
            this.cmbPicType.Visible = (bool)resources.GetObject("cmbPicType.Visible");
            this.cmbPicType.SelectedIndexChanged += new System.EventHandler(this.cmbPicType_SelectedIndexChanged);
            base.AcceptButton = this.btnOk;
            base.AccessibleDescription = resources.GetString("$this.AccessibleDescription");
            base.AccessibleName = resources.GetString("$this.AccessibleName");
            this.AutoScaleBaseSize = (System.Drawing.Size)resources.GetObject("$this.AutoScaleBaseSize");
            this.AutoScroll = (bool)resources.GetObject("$this.AutoScroll");
            base.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("$this.AutoScrollMargin");
            base.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("$this.AutoScrollMinSize");
            this.BackgroundImage = (System.Drawing.Image)resources.GetObject("$this.BackgroundImage");
            base.CancelButton = this.btnCancel;
            base.ClientSize = (System.Drawing.Size)resources.GetObject("$this.ClientSize");
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.btnOk);
            base.Controls.Add(this.btnCancel);
            base.Enabled = (bool)resources.GetObject("$this.Enabled");
            this.Font = (System.Drawing.Font)resources.GetObject("$this.Font");
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            base.Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
            base.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("$this.ImeMode");
            base.Location = (System.Drawing.Point)resources.GetObject("$this.Location");
            base.MaximizeBox = false;
            this.MaximumSize = (System.Drawing.Size)resources.GetObject("$this.MaximumSize");
            base.MinimizeBox = false;
            this.MinimumSize = (System.Drawing.Size)resources.GetObject("$this.MinimumSize");
            base.Name = "DlgPicture";
            this.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("$this.RightToLeft");
            base.StartPosition = (System.Windows.Forms.FormStartPosition)resources.GetObject("$this.StartPosition");
            this.Text = resources.GetString("$this.Text");
            base.Load += new System.EventHandler(this.DlgPicture_Load);
            this.panel1.ResumeLayout(false);
            this.numFileIndex.EndInit();
            base.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.CheckBox chkGrayscale;
        private System.Windows.Forms.ComboBox cmbPicType;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.NumericUpDown numFileIndex;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.TextBox txtCellEnd;
        private System.Windows.Forms.TextBox txtCellStart;
    }
}