namespace Thyt.TiPLM.UIL.PPM.PPCardModeling {
    partial class FrmTmpCompare {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary> 
        ///          
        private void InitializeComponent() {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(FrmTmpCompare));
            this.pnlLeft = new System.Windows.Forms.Panel();
            this.pnlLeftEx = new System.Windows.Forms.Panel();
            this.lab_Same = new System.Windows.Forms.Label();
            this.lab_Diff = new System.Windows.Forms.Label();
            this.lab_Card1 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.splitter2 = new System.Windows.Forms.Splitter();
            this.label1 = new System.Windows.Forms.Label();
            this.splitter1 = new System.Windows.Forms.Splitter();
            this.pnlRight = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.splitter3 = new System.Windows.Forms.Splitter();
            this.label2 = new System.Windows.Forms.Label();
            this.pnlRightEx = new System.Windows.Forms.Panel();
            this.lab_Gone = new System.Windows.Forms.Label();
            this.lab_Has = new System.Windows.Forms.Label();
            this.lab_Card2 = new System.Windows.Forms.Label();
            this.pnlLeft.SuspendLayout();
            this.pnlLeftEx.SuspendLayout();
            this.panel1.SuspendLayout();
            this.pnlRight.SuspendLayout();
            this.panel2.SuspendLayout();
            this.pnlRightEx.SuspendLayout();
            base.SuspendLayout();
            this.pnlLeft.AccessibleDescription = resources.GetString("pnlLeft.AccessibleDescription");
            this.pnlLeft.AccessibleName = resources.GetString("pnlLeft.AccessibleName");
            this.pnlLeft.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("pnlLeft.Anchor");
            this.pnlLeft.AutoScroll = (bool)resources.GetObject("pnlLeft.AutoScroll");
            this.pnlLeft.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("pnlLeft.AutoScrollMargin");
            this.pnlLeft.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("pnlLeft.AutoScrollMinSize");
            this.pnlLeft.BackgroundImage = (System.Drawing.Image)resources.GetObject("pnlLeft.BackgroundImage");
            this.pnlLeft.Controls.Add(this.pnlLeftEx);
            this.pnlLeft.Controls.Add(this.panel1);
            this.pnlLeft.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("pnlLeft.Dock");
            this.pnlLeft.Enabled = (bool)resources.GetObject("pnlLeft.Enabled");
            this.pnlLeft.Font = (System.Drawing.Font)resources.GetObject("pnlLeft.Font");
            this.pnlLeft.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("pnlLeft.ImeMode");
            this.pnlLeft.Location = (System.Drawing.Point)resources.GetObject("pnlLeft.Location");
            this.pnlLeft.Name = "pnlLeft";
            this.pnlLeft.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("pnlLeft.RightToLeft");
            this.pnlLeft.Size = (System.Drawing.Size)resources.GetObject("pnlLeft.Size");
            this.pnlLeft.TabIndex = (int)resources.GetObject("pnlLeft.TabIndex");
            this.pnlLeft.Text = resources.GetString("pnlLeft.Text");
            this.pnlLeft.Visible = (bool)resources.GetObject("pnlLeft.Visible");
            this.pnlLeftEx.AccessibleDescription = resources.GetString("pnlLeftEx.AccessibleDescription");
            this.pnlLeftEx.AccessibleName = resources.GetString("pnlLeftEx.AccessibleName");
            this.pnlLeftEx.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("pnlLeftEx.Anchor");
            this.pnlLeftEx.AutoScroll = (bool)resources.GetObject("pnlLeftEx.AutoScroll");
            this.pnlLeftEx.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("pnlLeftEx.AutoScrollMargin");
            this.pnlLeftEx.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("pnlLeftEx.AutoScrollMinSize");
            this.pnlLeftEx.BackgroundImage = (System.Drawing.Image)resources.GetObject("pnlLeftEx.BackgroundImage");
            this.pnlLeftEx.Controls.Add(this.lab_Same);
            this.pnlLeftEx.Controls.Add(this.lab_Diff);
            this.pnlLeftEx.Controls.Add(this.lab_Card1);
            this.pnlLeftEx.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("pnlLeftEx.Dock");
            this.pnlLeftEx.Enabled = (bool)resources.GetObject("pnlLeftEx.Enabled");
            this.pnlLeftEx.Font = (System.Drawing.Font)resources.GetObject("pnlLeftEx.Font");
            this.pnlLeftEx.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("pnlLeftEx.ImeMode");
            this.pnlLeftEx.Location = (System.Drawing.Point)resources.GetObject("pnlLeftEx.Location");
            this.pnlLeftEx.Name = "pnlLeftEx";
            this.pnlLeftEx.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("pnlLeftEx.RightToLeft");
            this.pnlLeftEx.Size = (System.Drawing.Size)resources.GetObject("pnlLeftEx.Size");
            this.pnlLeftEx.TabIndex = (int)resources.GetObject("pnlLeftEx.TabIndex");
            this.pnlLeftEx.Text = resources.GetString("pnlLeftEx.Text");
            this.pnlLeftEx.Visible = (bool)resources.GetObject("pnlLeftEx.Visible");
            this.lab_Same.AccessibleDescription = resources.GetString("lab_Same.AccessibleDescription");
            this.lab_Same.AccessibleName = resources.GetString("lab_Same.AccessibleName");
            this.lab_Same.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("lab_Same.Anchor");
            this.lab_Same.AutoSize = (bool)resources.GetObject("lab_Same.AutoSize");
            this.lab_Same.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lab_Same.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("lab_Same.Dock");
            this.lab_Same.Enabled = (bool)resources.GetObject("lab_Same.Enabled");
            this.lab_Same.Font = (System.Drawing.Font)resources.GetObject("lab_Same.Font");
            this.lab_Same.ForeColor = System.Drawing.Color.Black;
            this.lab_Same.Image = (System.Drawing.Image)resources.GetObject("lab_Same.Image");
            this.lab_Same.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Same.ImageAlign");
            this.lab_Same.ImageIndex = (int)resources.GetObject("lab_Same.ImageIndex");
            this.lab_Same.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("lab_Same.ImeMode");
            this.lab_Same.Location = (System.Drawing.Point)resources.GetObject("lab_Same.Location");
            this.lab_Same.Name = "lab_Same";
            this.lab_Same.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("lab_Same.RightToLeft");
            this.lab_Same.Size = (System.Drawing.Size)resources.GetObject("lab_Same.Size");
            this.lab_Same.TabIndex = (int)resources.GetObject("lab_Same.TabIndex");
            this.lab_Same.Text = resources.GetString("lab_Same.Text");
            this.lab_Same.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Same.TextAlign");
            this.lab_Same.Visible = (bool)resources.GetObject("lab_Same.Visible");
            this.lab_Diff.AccessibleDescription = resources.GetString("lab_Diff.AccessibleDescription");
            this.lab_Diff.AccessibleName = resources.GetString("lab_Diff.AccessibleName");
            this.lab_Diff.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("lab_Diff.Anchor");
            this.lab_Diff.AutoSize = (bool)resources.GetObject("lab_Diff.AutoSize");
            this.lab_Diff.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lab_Diff.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("lab_Diff.Dock");
            this.lab_Diff.Enabled = (bool)resources.GetObject("lab_Diff.Enabled");
            this.lab_Diff.Font = (System.Drawing.Font)resources.GetObject("lab_Diff.Font");
            this.lab_Diff.ForeColor = System.Drawing.Color.Blue;
            this.lab_Diff.Image = (System.Drawing.Image)resources.GetObject("lab_Diff.Image");
            this.lab_Diff.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Diff.ImageAlign");
            this.lab_Diff.ImageIndex = (int)resources.GetObject("lab_Diff.ImageIndex");
            this.lab_Diff.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("lab_Diff.ImeMode");
            this.lab_Diff.Location = (System.Drawing.Point)resources.GetObject("lab_Diff.Location");
            this.lab_Diff.Name = "lab_Diff";
            this.lab_Diff.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("lab_Diff.RightToLeft");
            this.lab_Diff.Size = (System.Drawing.Size)resources.GetObject("lab_Diff.Size");
            this.lab_Diff.TabIndex = (int)resources.GetObject("lab_Diff.TabIndex");
            this.lab_Diff.Text = resources.GetString("lab_Diff.Text");
            this.lab_Diff.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Diff.TextAlign");
            this.lab_Diff.Visible = (bool)resources.GetObject("lab_Diff.Visible");
            this.lab_Card1.AccessibleDescription = resources.GetString("lab_Card1.AccessibleDescription");
            this.lab_Card1.AccessibleName = resources.GetString("lab_Card1.AccessibleName");
            this.lab_Card1.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("lab_Card1.Anchor");
            this.lab_Card1.AutoSize = (bool)resources.GetObject("lab_Card1.AutoSize");
            this.lab_Card1.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("lab_Card1.Dock");
            this.lab_Card1.Enabled = (bool)resources.GetObject("lab_Card1.Enabled");
            this.lab_Card1.Font = (System.Drawing.Font)resources.GetObject("lab_Card1.Font");
            this.lab_Card1.Image = (System.Drawing.Image)resources.GetObject("lab_Card1.Image");
            this.lab_Card1.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Card1.ImageAlign");
            this.lab_Card1.ImageIndex = (int)resources.GetObject("lab_Card1.ImageIndex");
            this.lab_Card1.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("lab_Card1.ImeMode");
            this.lab_Card1.Location = (System.Drawing.Point)resources.GetObject("lab_Card1.Location");
            this.lab_Card1.Name = "lab_Card1";
            this.lab_Card1.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("lab_Card1.RightToLeft");
            this.lab_Card1.Size = (System.Drawing.Size)resources.GetObject("lab_Card1.Size");
            this.lab_Card1.TabIndex = (int)resources.GetObject("lab_Card1.TabIndex");
            this.lab_Card1.Text = resources.GetString("lab_Card1.Text");
            this.lab_Card1.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Card1.TextAlign");
            this.lab_Card1.Visible = (bool)resources.GetObject("lab_Card1.Visible");
            this.panel1.AccessibleDescription = resources.GetString("panel1.AccessibleDescription");
            this.panel1.AccessibleName = resources.GetString("panel1.AccessibleName");
            this.panel1.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("panel1.Anchor");
            this.panel1.AutoScroll = (bool)resources.GetObject("panel1.AutoScroll");
            this.panel1.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("panel1.AutoScrollMargin");
            this.panel1.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("panel1.AutoScrollMinSize");
            this.panel1.BackgroundImage = (System.Drawing.Image)resources.GetObject("panel1.BackgroundImage");
            this.panel1.Controls.Add(this.splitter2);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("panel1.Dock");
            this.panel1.Enabled = (bool)resources.GetObject("panel1.Enabled");
            this.panel1.Font = (System.Drawing.Font)resources.GetObject("panel1.Font");
            this.panel1.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("panel1.ImeMode");
            this.panel1.Location = (System.Drawing.Point)resources.GetObject("panel1.Location");
            this.panel1.Name = "panel1";
            this.panel1.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("panel1.RightToLeft");
            this.panel1.Size = (System.Drawing.Size)resources.GetObject("panel1.Size");
            this.panel1.TabIndex = (int)resources.GetObject("panel1.TabIndex");
            this.panel1.Text = resources.GetString("panel1.Text");
            this.panel1.Visible = (bool)resources.GetObject("panel1.Visible");
            this.splitter2.AccessibleDescription = resources.GetString("splitter2.AccessibleDescription");
            this.splitter2.AccessibleName = resources.GetString("splitter2.AccessibleName");
            this.splitter2.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("splitter2.Anchor");
            this.splitter2.BackgroundImage = (System.Drawing.Image)resources.GetObject("splitter2.BackgroundImage");
            this.splitter2.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("splitter2.Dock");
            this.splitter2.Enabled = (bool)resources.GetObject("splitter2.Enabled");
            this.splitter2.Font = (System.Drawing.Font)resources.GetObject("splitter2.Font");
            this.splitter2.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("splitter2.ImeMode");
            this.splitter2.Location = (System.Drawing.Point)resources.GetObject("splitter2.Location");
            this.splitter2.MinExtra = (int)resources.GetObject("splitter2.MinExtra");
            this.splitter2.MinSize = (int)resources.GetObject("splitter2.MinSize");
            this.splitter2.Name = "splitter2";
            this.splitter2.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("splitter2.RightToLeft");
            this.splitter2.Size = (System.Drawing.Size)resources.GetObject("splitter2.Size");
            this.splitter2.TabIndex = (int)resources.GetObject("splitter2.TabIndex");
            this.splitter2.TabStop = false;
            this.splitter2.Visible = (bool)resources.GetObject("splitter2.Visible");
            this.label1.AccessibleDescription = resources.GetString("label1.AccessibleDescription");
            this.label1.AccessibleName = resources.GetString("label1.AccessibleName");
            this.label1.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("label1.Anchor");
            this.label1.AutoSize = (bool)resources.GetObject("label1.AutoSize");
            this.label1.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("label1.Dock");
            this.label1.Enabled = (bool)resources.GetObject("label1.Enabled");
            this.label1.Font = (System.Drawing.Font)resources.GetObject("label1.Font");
            this.label1.ForeColor = System.Drawing.Color.OrangeRed;
            this.label1.Image = (System.Drawing.Image)resources.GetObject("label1.Image");
            this.label1.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("label1.ImageAlign");
            this.label1.ImageIndex = (int)resources.GetObject("label1.ImageIndex");
            this.label1.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("label1.ImeMode");
            this.label1.Location = (System.Drawing.Point)resources.GetObject("label1.Location");
            this.label1.Name = "label1";
            this.label1.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("label1.RightToLeft");
            this.label1.Size = (System.Drawing.Size)resources.GetObject("label1.Size");
            this.label1.TabIndex = (int)resources.GetObject("label1.TabIndex");
            this.label1.Text = resources.GetString("label1.Text");
            this.label1.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("label1.TextAlign");
            this.label1.Visible = (bool)resources.GetObject("label1.Visible");
            this.splitter1.AccessibleDescription = resources.GetString("splitter1.AccessibleDescription");
            this.splitter1.AccessibleName = resources.GetString("splitter1.AccessibleName");
            this.splitter1.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("splitter1.Anchor");
            this.splitter1.BackgroundImage = (System.Drawing.Image)resources.GetObject("splitter1.BackgroundImage");
            this.splitter1.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("splitter1.Dock");
            this.splitter1.Enabled = (bool)resources.GetObject("splitter1.Enabled");
            this.splitter1.Font = (System.Drawing.Font)resources.GetObject("splitter1.Font");
            this.splitter1.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("splitter1.ImeMode");
            this.splitter1.Location = (System.Drawing.Point)resources.GetObject("splitter1.Location");
            this.splitter1.MinExtra = (int)resources.GetObject("splitter1.MinExtra");
            this.splitter1.MinSize = (int)resources.GetObject("splitter1.MinSize");
            this.splitter1.Name = "splitter1";
            this.splitter1.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("splitter1.RightToLeft");
            this.splitter1.Size = (System.Drawing.Size)resources.GetObject("splitter1.Size");
            this.splitter1.TabIndex = (int)resources.GetObject("splitter1.TabIndex");
            this.splitter1.TabStop = false;
            this.splitter1.Visible = (bool)resources.GetObject("splitter1.Visible");
            this.pnlRight.AccessibleDescription = resources.GetString("pnlRight.AccessibleDescription");
            this.pnlRight.AccessibleName = resources.GetString("pnlRight.AccessibleName");
            this.pnlRight.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("pnlRight.Anchor");
            this.pnlRight.AutoScroll = (bool)resources.GetObject("pnlRight.AutoScroll");
            this.pnlRight.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("pnlRight.AutoScrollMargin");
            this.pnlRight.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("pnlRight.AutoScrollMinSize");
            this.pnlRight.BackgroundImage = (System.Drawing.Image)resources.GetObject("pnlRight.BackgroundImage");
            this.pnlRight.Controls.Add(this.panel2);
            this.pnlRight.Controls.Add(this.pnlRightEx);
            this.pnlRight.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("pnlRight.Dock");
            this.pnlRight.Enabled = (bool)resources.GetObject("pnlRight.Enabled");
            this.pnlRight.Font = (System.Drawing.Font)resources.GetObject("pnlRight.Font");
            this.pnlRight.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("pnlRight.ImeMode");
            this.pnlRight.Location = (System.Drawing.Point)resources.GetObject("pnlRight.Location");
            this.pnlRight.Name = "pnlRight";
            this.pnlRight.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("pnlRight.RightToLeft");
            this.pnlRight.Size = (System.Drawing.Size)resources.GetObject("pnlRight.Size");
            this.pnlRight.TabIndex = (int)resources.GetObject("pnlRight.TabIndex");
            this.pnlRight.Text = resources.GetString("pnlRight.Text");
            this.pnlRight.Visible = (bool)resources.GetObject("pnlRight.Visible");
            this.panel2.AccessibleDescription = resources.GetString("panel2.AccessibleDescription");
            this.panel2.AccessibleName = resources.GetString("panel2.AccessibleName");
            this.panel2.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("panel2.Anchor");
            this.panel2.AutoScroll = (bool)resources.GetObject("panel2.AutoScroll");
            this.panel2.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("panel2.AutoScrollMargin");
            this.panel2.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("panel2.AutoScrollMinSize");
            this.panel2.BackgroundImage = (System.Drawing.Image)resources.GetObject("panel2.BackgroundImage");
            this.panel2.Controls.Add(this.splitter3);
            this.panel2.Controls.Add(this.label2);
            this.panel2.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("panel2.Dock");
            this.panel2.Enabled = (bool)resources.GetObject("panel2.Enabled");
            this.panel2.Font = (System.Drawing.Font)resources.GetObject("panel2.Font");
            this.panel2.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("panel2.ImeMode");
            this.panel2.Location = (System.Drawing.Point)resources.GetObject("panel2.Location");
            this.panel2.Name = "panel2";
            this.panel2.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("panel2.RightToLeft");
            this.panel2.Size = (System.Drawing.Size)resources.GetObject("panel2.Size");
            this.panel2.TabIndex = (int)resources.GetObject("panel2.TabIndex");
            this.panel2.Text = resources.GetString("panel2.Text");
            this.panel2.Visible = (bool)resources.GetObject("panel2.Visible");
            this.splitter3.AccessibleDescription = resources.GetString("splitter3.AccessibleDescription");
            this.splitter3.AccessibleName = resources.GetString("splitter3.AccessibleName");
            this.splitter3.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("splitter3.Anchor");
            this.splitter3.BackgroundImage = (System.Drawing.Image)resources.GetObject("splitter3.BackgroundImage");
            this.splitter3.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("splitter3.Dock");
            this.splitter3.Enabled = (bool)resources.GetObject("splitter3.Enabled");
            this.splitter3.Font = (System.Drawing.Font)resources.GetObject("splitter3.Font");
            this.splitter3.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("splitter3.ImeMode");
            this.splitter3.Location = (System.Drawing.Point)resources.GetObject("splitter3.Location");
            this.splitter3.MinExtra = (int)resources.GetObject("splitter3.MinExtra");
            this.splitter3.MinSize = (int)resources.GetObject("splitter3.MinSize");
            this.splitter3.Name = "splitter3";
            this.splitter3.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("splitter3.RightToLeft");
            this.splitter3.Size = (System.Drawing.Size)resources.GetObject("splitter3.Size");
            this.splitter3.TabIndex = (int)resources.GetObject("splitter3.TabIndex");
            this.splitter3.TabStop = false;
            this.splitter3.Visible = (bool)resources.GetObject("splitter3.Visible");
            this.label2.AccessibleDescription = resources.GetString("label2.AccessibleDescription");
            this.label2.AccessibleName = resources.GetString("label2.AccessibleName");
            this.label2.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("label2.Anchor");
            this.label2.AutoSize = (bool)resources.GetObject("label2.AutoSize");
            this.label2.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("label2.Dock");
            this.label2.Enabled = (bool)resources.GetObject("label2.Enabled");
            this.label2.Font = (System.Drawing.Font)resources.GetObject("label2.Font");
            this.label2.ForeColor = System.Drawing.Color.OrangeRed;
            this.label2.Image = (System.Drawing.Image)resources.GetObject("label2.Image");
            this.label2.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("label2.ImageAlign");
            this.label2.ImageIndex = (int)resources.GetObject("label2.ImageIndex");
            this.label2.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("label2.ImeMode");
            this.label2.Location = (System.Drawing.Point)resources.GetObject("label2.Location");
            this.label2.Name = "label2";
            this.label2.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("label2.RightToLeft");
            this.label2.Size = (System.Drawing.Size)resources.GetObject("label2.Size");
            this.label2.TabIndex = (int)resources.GetObject("label2.TabIndex");
            this.label2.Text = resources.GetString("label2.Text");
            this.label2.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("label2.TextAlign");
            this.label2.Visible = (bool)resources.GetObject("label2.Visible");
            this.pnlRightEx.AccessibleDescription = resources.GetString("pnlRightEx.AccessibleDescription");
            this.pnlRightEx.AccessibleName = resources.GetString("pnlRightEx.AccessibleName");
            this.pnlRightEx.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("pnlRightEx.Anchor");
            this.pnlRightEx.AutoScroll = (bool)resources.GetObject("pnlRightEx.AutoScroll");
            this.pnlRightEx.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("pnlRightEx.AutoScrollMargin");
            this.pnlRightEx.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("pnlRightEx.AutoScrollMinSize");
            this.pnlRightEx.BackgroundImage = (System.Drawing.Image)resources.GetObject("pnlRightEx.BackgroundImage");
            this.pnlRightEx.Controls.Add(this.lab_Gone);
            this.pnlRightEx.Controls.Add(this.lab_Has);
            this.pnlRightEx.Controls.Add(this.lab_Card2);
            this.pnlRightEx.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("pnlRightEx.Dock");
            this.pnlRightEx.Enabled = (bool)resources.GetObject("pnlRightEx.Enabled");
            this.pnlRightEx.Font = (System.Drawing.Font)resources.GetObject("pnlRightEx.Font");
            this.pnlRightEx.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("pnlRightEx.ImeMode");
            this.pnlRightEx.Location = (System.Drawing.Point)resources.GetObject("pnlRightEx.Location");
            this.pnlRightEx.Name = "pnlRightEx";
            this.pnlRightEx.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("pnlRightEx.RightToLeft");
            this.pnlRightEx.Size = (System.Drawing.Size)resources.GetObject("pnlRightEx.Size");
            this.pnlRightEx.TabIndex = (int)resources.GetObject("pnlRightEx.TabIndex");
            this.pnlRightEx.Text = resources.GetString("pnlRightEx.Text");
            this.pnlRightEx.Visible = (bool)resources.GetObject("pnlRightEx.Visible");
            this.lab_Gone.AccessibleDescription = resources.GetString("lab_Gone.AccessibleDescription");
            this.lab_Gone.AccessibleName = resources.GetString("lab_Gone.AccessibleName");
            this.lab_Gone.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("lab_Gone.Anchor");
            this.lab_Gone.AutoSize = (bool)resources.GetObject("lab_Gone.AutoSize");
            this.lab_Gone.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lab_Gone.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("lab_Gone.Dock");
            this.lab_Gone.Enabled = (bool)resources.GetObject("lab_Gone.Enabled");
            this.lab_Gone.Font = (System.Drawing.Font)resources.GetObject("lab_Gone.Font");
            this.lab_Gone.ForeColor = System.Drawing.Color.Fuchsia;
            this.lab_Gone.Image = (System.Drawing.Image)resources.GetObject("lab_Gone.Image");
            this.lab_Gone.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Gone.ImageAlign");
            this.lab_Gone.ImageIndex = (int)resources.GetObject("lab_Gone.ImageIndex");
            this.lab_Gone.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("lab_Gone.ImeMode");
            this.lab_Gone.Location = (System.Drawing.Point)resources.GetObject("lab_Gone.Location");
            this.lab_Gone.Name = "lab_Gone";
            this.lab_Gone.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("lab_Gone.RightToLeft");
            this.lab_Gone.Size = (System.Drawing.Size)resources.GetObject("lab_Gone.Size");
            this.lab_Gone.TabIndex = (int)resources.GetObject("lab_Gone.TabIndex");
            this.lab_Gone.Text = resources.GetString("lab_Gone.Text");
            this.lab_Gone.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Gone.TextAlign");
            this.lab_Gone.Visible = (bool)resources.GetObject("lab_Gone.Visible");
            this.lab_Has.AccessibleDescription = resources.GetString("lab_Has.AccessibleDescription");
            this.lab_Has.AccessibleName = resources.GetString("lab_Has.AccessibleName");
            this.lab_Has.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("lab_Has.Anchor");
            this.lab_Has.AutoSize = (bool)resources.GetObject("lab_Has.AutoSize");
            this.lab_Has.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lab_Has.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("lab_Has.Dock");
            this.lab_Has.Enabled = (bool)resources.GetObject("lab_Has.Enabled");
            this.lab_Has.Font = (System.Drawing.Font)resources.GetObject("lab_Has.Font");
            this.lab_Has.ForeColor = System.Drawing.Color.Red;
            this.lab_Has.Image = (System.Drawing.Image)resources.GetObject("lab_Has.Image");
            this.lab_Has.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Has.ImageAlign");
            this.lab_Has.ImageIndex = (int)resources.GetObject("lab_Has.ImageIndex");
            this.lab_Has.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("lab_Has.ImeMode");
            this.lab_Has.Location = (System.Drawing.Point)resources.GetObject("lab_Has.Location");
            this.lab_Has.Name = "lab_Has";
            this.lab_Has.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("lab_Has.RightToLeft");
            this.lab_Has.Size = (System.Drawing.Size)resources.GetObject("lab_Has.Size");
            this.lab_Has.TabIndex = (int)resources.GetObject("lab_Has.TabIndex");
            this.lab_Has.Text = resources.GetString("lab_Has.Text");
            this.lab_Has.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Has.TextAlign");
            this.lab_Has.Visible = (bool)resources.GetObject("lab_Has.Visible");
            this.lab_Card2.AccessibleDescription = resources.GetString("lab_Card2.AccessibleDescription");
            this.lab_Card2.AccessibleName = resources.GetString("lab_Card2.AccessibleName");
            this.lab_Card2.Anchor = (System.Windows.Forms.AnchorStyles)resources.GetObject("lab_Card2.Anchor");
            this.lab_Card2.AutoSize = (bool)resources.GetObject("lab_Card2.AutoSize");
            this.lab_Card2.Dock = (System.Windows.Forms.DockStyle)resources.GetObject("lab_Card2.Dock");
            this.lab_Card2.Enabled = (bool)resources.GetObject("lab_Card2.Enabled");
            this.lab_Card2.Font = (System.Drawing.Font)resources.GetObject("lab_Card2.Font");
            this.lab_Card2.Image = (System.Drawing.Image)resources.GetObject("lab_Card2.Image");
            this.lab_Card2.ImageAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Card2.ImageAlign");
            this.lab_Card2.ImageIndex = (int)resources.GetObject("lab_Card2.ImageIndex");
            this.lab_Card2.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("lab_Card2.ImeMode");
            this.lab_Card2.Location = (System.Drawing.Point)resources.GetObject("lab_Card2.Location");
            this.lab_Card2.Name = "lab_Card2";
            this.lab_Card2.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("lab_Card2.RightToLeft");
            this.lab_Card2.Size = (System.Drawing.Size)resources.GetObject("lab_Card2.Size");
            this.lab_Card2.TabIndex = (int)resources.GetObject("lab_Card2.TabIndex");
            this.lab_Card2.Text = resources.GetString("lab_Card2.Text");
            this.lab_Card2.TextAlign = (System.Drawing.ContentAlignment)resources.GetObject("lab_Card2.TextAlign");
            this.lab_Card2.Visible = (bool)resources.GetObject("lab_Card2.Visible");
            base.AccessibleDescription = resources.GetString("$this.AccessibleDescription");
            base.AccessibleName = resources.GetString("$this.AccessibleName");
            this.AutoScaleBaseSize = (System.Drawing.Size)resources.GetObject("$this.AutoScaleBaseSize");
            this.AutoScroll = (bool)resources.GetObject("$this.AutoScroll");
            base.AutoScrollMargin = (System.Drawing.Size)resources.GetObject("$this.AutoScrollMargin");
            base.AutoScrollMinSize = (System.Drawing.Size)resources.GetObject("$this.AutoScrollMinSize");
            this.BackgroundImage = (System.Drawing.Image)resources.GetObject("$this.BackgroundImage");
            base.ClientSize = (System.Drawing.Size)resources.GetObject("$this.ClientSize");
            base.Controls.Add(this.pnlRight);
            base.Controls.Add(this.splitter1);
            base.Controls.Add(this.pnlLeft);
            base.Enabled = (bool)resources.GetObject("$this.Enabled");
            this.Font = (System.Drawing.Font)resources.GetObject("$this.Font");
            base.Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
            base.ImeMode = (System.Windows.Forms.ImeMode)resources.GetObject("$this.ImeMode");
            base.Location = (System.Drawing.Point)resources.GetObject("$this.Location");
            this.MaximumSize = (System.Drawing.Size)resources.GetObject("$this.MaximumSize");
            this.MinimumSize = (System.Drawing.Size)resources.GetObject("$this.MinimumSize");
            base.Name = "FrmTmpCompare";
            this.RightToLeft = (System.Windows.Forms.RightToLeft)resources.GetObject("$this.RightToLeft");
            base.StartPosition = (System.Windows.Forms.FormStartPosition)resources.GetObject("$this.StartPosition");
            this.Text = resources.GetString("$this.Text");
            base.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            base.SizeChanged += new System.EventHandler(this.FrmTmpCompare_SizeChanged);
            base.Load += new System.EventHandler(this.FrmTmpCompare_Load);
            this.pnlLeft.ResumeLayout(false);
            this.pnlLeftEx.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.pnlRight.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.pnlRightEx.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        #endregion  
        private System.Windows.Forms.Label lab_Card1;
        private System.Windows.Forms.Label lab_Card2;
        private System.Windows.Forms.Label lab_Diff;
        private System.Windows.Forms.Label lab_Gone;
        private System.Windows.Forms.Label lab_Has;
        private System.Windows.Forms.Label lab_Same;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel pnlLeft;
        private System.Windows.Forms.Panel pnlLeftEx;
        private System.Windows.Forms.Panel pnlRight;
        private System.Windows.Forms.Panel pnlRightEx;
        private System.Windows.Forms.Splitter splitter1;
        private System.Windows.Forms.Splitter splitter2;
        private System.Windows.Forms.Splitter splitter3;
    }
}