namespace Thyt.TiPLM.UIL.Resource.Common {
    partial class FrmRESPicture {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>

        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary> 
        ///          

        private void InitializeComponent() {
            this.splTree = new Thyt.TiPLM.UIL.Controls.SplitterPLM();
            this.pnlMain = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.pnlNatural = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.gbProperty = new Thyt.TiPLM.UIL.Controls.GroupBoxPLM();
            this.pnlProperty = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.lblAlias = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.lblCreator = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.lblModifier = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.lblSize = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.lblCreateTime = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.lblModifyTime = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.lblDes = new Thyt.TiPLM.UIL.Controls.LabelPLM();
            this.splPro = new Thyt.TiPLM.UIL.Controls.SplitterPLM();
            this.gbLargeImage = new Thyt.TiPLM.UIL.Controls.GroupBoxPLM();
            this.pnlLargeImage = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.pb = new Thyt.TiPLM.UIL.Controls.PictureBoxPLM();
            this.cmuOnPic = new System.Windows.Forms.ContextMenu();
            this.miNormal = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miStretchImage = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miAutoSize = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miCenterImage = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.splPic = new Thyt.TiPLM.UIL.Controls.SplitterPLM();
            this.pnlMiniature = new Thyt.TiPLM.UIL.Controls.PanelPLM();
            this.lvwImage = new Thyt.TiPLM.UIL.Common.SortableListView();
            this.picture = new System.Windows.Forms.ColumnHeader();
            this.pictureSize = new System.Windows.Forms.ColumnHeader();
            this.pictureCreator = new System.Windows.Forms.ColumnHeader();
            this.pictureCreateTime = new System.Windows.Forms.ColumnHeader();
            this.pictureModifier = new System.Windows.Forms.ColumnHeader();
            this.pictureModifyTime = new System.Windows.Forms.ColumnHeader();
            this.pictureDescrip = new System.Windows.Forms.ColumnHeader();
            this.cmuPicture = new System.Windows.Forms.ContextMenu();
            this.miProperty = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miView = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miLargeIcon = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miSmallIcon = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miList = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miDetails = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miRefresh = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miShowDock = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.miSelected = new Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx();
            this.pnlMain.SuspendLayout();
            this.pnlNatural.SuspendLayout();
            this.gbProperty.BeginInit();
            this.gbProperty.SuspendLayout();
            this.pnlProperty.SuspendLayout();
            this.gbLargeImage.BeginInit();
            this.gbLargeImage.SuspendLayout();
            this.pnlLargeImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)this.pb).BeginInit();
            this.pnlMiniature.SuspendLayout();
            base.SuspendLayout();
            this.splTree.Location = new System.Drawing.Point(0, 0);
            this.splTree.Name = "splTree";
            this.splTree.Size = new System.Drawing.Size(5, 0x1b2);
            this.splTree.TabIndex = 1;
            this.splTree.TabStop = false;
            this.pnlMain.Controls.Add(this.pnlNatural);
            this.pnlMain.Controls.Add(this.splPic);
            this.pnlMain.Controls.Add(this.pnlMiniature);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(5, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(0x277, 0x1b2);
            this.pnlMain.TabIndex = 2;
            this.pnlNatural.Controls.Add(this.gbProperty);
            this.pnlNatural.Controls.Add(this.splPro);
            this.pnlNatural.Controls.Add(this.gbLargeImage);
            this.pnlNatural.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlNatural.Location = new System.Drawing.Point(2, 0xb2);
            this.pnlNatural.Name = "pnlNatural";
            this.pnlNatural.Size = new System.Drawing.Size(0x273, 0xfe);
            this.pnlNatural.TabIndex = 2;
            this.gbProperty.Controls.Add(this.pnlProperty);
            this.gbProperty.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gbProperty.Location = new System.Drawing.Point(0x137, 2);
            this.gbProperty.Name = "gbProperty";
            this.gbProperty.Size = new System.Drawing.Size(0x13a, 250);
            this.gbProperty.TabIndex = 2;
            this.gbProperty.Text = "图片属性";
            this.pnlProperty.Controls.Add(this.lblAlias);
            this.pnlProperty.Controls.Add(this.lblCreator);
            this.pnlProperty.Controls.Add(this.lblModifier);
            this.pnlProperty.Controls.Add(this.lblSize);
            this.pnlProperty.Controls.Add(this.lblCreateTime);
            this.pnlProperty.Controls.Add(this.lblModifyTime);
            this.pnlProperty.Controls.Add(this.lblDes);
            this.pnlProperty.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlProperty.Location = new System.Drawing.Point(2, 0x16);
            this.pnlProperty.Name = "pnlProperty";
            this.pnlProperty.Size = new System.Drawing.Size(310, 0xe2);
            this.pnlProperty.TabIndex = 0;
            this.lblAlias.Location = new System.Drawing.Point(0x10, 9);
            this.lblAlias.Name = "lblAlias";
            this.lblAlias.Size = new System.Drawing.Size(0x10c, 0x11);
            this.lblAlias.TabIndex = 0;
            this.lblAlias.Text = "名称:";
            this.lblCreator.Location = new System.Drawing.Point(0x10, 60);
            this.lblCreator.Name = "lblCreator";
            this.lblCreator.Size = new System.Drawing.Size(0x10c, 0x11);
            this.lblCreator.TabIndex = 2;
            this.lblCreator.Text = "创建者:";
            this.lblModifier.Location = new System.Drawing.Point(0x10, 0x6f);
            this.lblModifier.Name = "lblModifier";
            this.lblModifier.Size = new System.Drawing.Size(0x10c, 0x12);
            this.lblModifier.TabIndex = 6;
            this.lblModifier.Text = "修改者:";
            this.lblSize.Location = new System.Drawing.Point(0x10, 0x22);
            this.lblSize.Name = "lblSize";
            this.lblSize.Size = new System.Drawing.Size(0x10c, 0x11);
            this.lblSize.TabIndex = 1;
            this.lblSize.Text = "大小：";
            this.lblCreateTime.Location = new System.Drawing.Point(0x10, 0x56);
            this.lblCreateTime.Name = "lblCreateTime";
            this.lblCreateTime.Size = new System.Drawing.Size(0x10c, 0x11);
            this.lblCreateTime.TabIndex = 3;
            this.lblCreateTime.Text = "创建时间:";
            this.lblModifyTime.Location = new System.Drawing.Point(0x10, 0x89);
            this.lblModifyTime.Name = "lblModifyTime";
            this.lblModifyTime.Size = new System.Drawing.Size(0x10c, 0x11);
            this.lblModifyTime.TabIndex = 7;
            this.lblModifyTime.Text = "修改时间:";
            this.lblDes.Location = new System.Drawing.Point(0x10, 0xa3);
            this.lblDes.Name = "lblDes";
            this.lblDes.Size = new System.Drawing.Size(0x10c, 0x52);
            this.lblDes.TabIndex = 5;
            this.lblDes.Text = "描述：";
            this.splPro.Location = new System.Drawing.Point(0x132, 2);
            this.splPro.Name = "splPro";
            this.splPro.Size = new System.Drawing.Size(5, 250);
            this.splPro.TabIndex = 1;
            this.splPro.TabStop = false;
            this.gbLargeImage.Controls.Add(this.pnlLargeImage);
            this.gbLargeImage.Dock = System.Windows.Forms.DockStyle.Left;
            this.gbLargeImage.Location = new System.Drawing.Point(2, 2);
            this.gbLargeImage.Name = "gbLargeImage";
            this.gbLargeImage.Size = new System.Drawing.Size(0x130, 250);
            this.gbLargeImage.TabIndex = 0;
            this.gbLargeImage.Text = "图片";
            this.pnlLargeImage.Controls.Add(this.pb);
            this.pnlLargeImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlLargeImage.Location = new System.Drawing.Point(2, 0x16);
            this.pnlLargeImage.Name = "pnlLargeImage";
            this.pnlLargeImage.Size = new System.Drawing.Size(300, 0xe2);
            this.pnlLargeImage.TabIndex = 0;
            this.pnlLargeImage.Resize += new System.EventHandler(this.pnlLargeImage_Resize);
            this.pb.ContextMenu = this.cmuOnPic;
            this.pb.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pb.Location = new System.Drawing.Point(2, 2);
            this.pb.Name = "pb";
            this.pb.Size = new System.Drawing.Size(0x128, 0xde);
            this.pb.TabIndex = 0;
            this.pb.TabStop = false;
            this.cmuOnPic.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] { this.miNormal, this.miStretchImage, this.miAutoSize, this.miCenterImage });
            this.miNormal.ClickHandler = null;
            this.miNormal.EventHandlerName = null;
            this.miNormal.Icon = null;
            this.miNormal.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miNormal.ImageIndex = -1;
            this.miNormal.ImageList = null;
            this.miNormal.Index = 0;
            this.miNormal.OwnerDraw = true;
            this.miNormal.ShortcutText = "";
            this.miNormal.Text = "普通(&N)";
            this.miNormal.Click += new System.EventHandler(this.miNormal_Click);
            this.miStretchImage.ClickHandler = null;
            this.miStretchImage.EventHandlerName = null;
            this.miStretchImage.Icon = null;
            this.miStretchImage.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miStretchImage.ImageIndex = -1;
            this.miStretchImage.ImageList = null;
            this.miStretchImage.Index = 1;
            this.miStretchImage.OwnerDraw = true;
            this.miStretchImage.ShortcutText = "";
            this.miStretchImage.Text = "拉伸(&S)";
            this.miStretchImage.Click += new System.EventHandler(this.miStretchImage_Click);
            this.miAutoSize.ClickHandler = null;
            this.miAutoSize.EventHandlerName = null;
            this.miAutoSize.Icon = null;
            this.miAutoSize.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miAutoSize.ImageIndex = -1;
            this.miAutoSize.ImageList = null;
            this.miAutoSize.Index = 2;
            this.miAutoSize.OwnerDraw = true;
            this.miAutoSize.ShortcutText = "";
            this.miAutoSize.Text = "自动大小(&A)";
            this.miAutoSize.Click += new System.EventHandler(this.miAutoSize_Click);
            this.miCenterImage.ClickHandler = null;
            this.miCenterImage.EventHandlerName = null;
            this.miCenterImage.Icon = null;
            this.miCenterImage.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miCenterImage.ImageIndex = -1;
            this.miCenterImage.ImageList = null;
            this.miCenterImage.Index = 3;
            this.miCenterImage.OwnerDraw = true;
            this.miCenterImage.ShortcutText = "";
            this.miCenterImage.Text = "居中(&C)";
            this.miCenterImage.Click += new System.EventHandler(this.miCenterImage_Click);
            this.splPic.Dock = System.Windows.Forms.DockStyle.Top;
            this.splPic.Location = new System.Drawing.Point(2, 0xad);
            this.splPic.Name = "splPic";
            this.splPic.Size = new System.Drawing.Size(0x273, 5);
            this.splPic.TabIndex = 1;
            this.splPic.TabStop = false;
            this.pnlMiniature.Controls.Add(this.lvwImage);
            this.pnlMiniature.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlMiniature.Location = new System.Drawing.Point(2, 2);
            this.pnlMiniature.Name = "pnlMiniature";
            this.pnlMiniature.Size = new System.Drawing.Size(0x273, 0xab);
            this.pnlMiniature.TabIndex = 0;
            this.lvwImage.AllowDrop = true;
            this.lvwImage.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] { this.picture, this.pictureSize, this.pictureCreator, this.pictureCreateTime, this.pictureModifier, this.pictureModifyTime, this.pictureDescrip });
            this.lvwImage.ContextMenu = this.cmuPicture;
            this.lvwImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lvwImage.FullRowSelect = true;
            this.lvwImage.HideSelection = false;
            this.lvwImage.Location = new System.Drawing.Point(2, 2);
            this.lvwImage.Name = "lvwImage";
            this.lvwImage.Size = new System.Drawing.Size(0x26f, 0xa7);
            this.lvwImage.SortingOrder = System.Windows.Forms.SortOrder.None;
            this.lvwImage.TabIndex = 0;
            this.lvwImage.UseCompatibleStateImageBehavior = false;
            this.lvwImage.View = System.Windows.Forms.View.Details;
            this.lvwImage.ItemDrag += new System.Windows.Forms.ItemDragEventHandler(this.lvwImage_ItemDrag);
            this.lvwImage.SelectedIndexChanged += new System.EventHandler(this.lvwImage_SelectedIndexChanged);
            this.lvwImage.DoubleClick += new System.EventHandler(this.lvwImage_DoubleClick);
            this.lvwImage.MouseUp += new System.Windows.Forms.MouseEventHandler(this.lvwImage_MouseUp);
            this.picture.Text = "图片";
            this.picture.Width = 100;
            this.pictureSize.Text = "图片大小";
            this.pictureCreator.Text = "创建者";
            this.pictureCreator.Width = 100;
            this.pictureCreateTime.Text = "创建时间";
            this.pictureCreateTime.Width = 150;
            this.pictureModifier.Text = "修改者";
            this.pictureModifier.Width = 100;
            this.pictureModifyTime.Text = "修改时间";
            this.pictureModifyTime.Width = 150;
            this.pictureDescrip.Text = "图片描述";
            this.pictureDescrip.Width = 150;
            this.cmuPicture.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] { this.miProperty, this.miView, this.miRefresh, this.miShowDock, this.miSelected });
            this.miProperty.ClickHandler = null;
            this.miProperty.EventHandlerName = null;
            this.miProperty.Icon = null;
            this.miProperty.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miProperty.ImageIndex = -1;
            this.miProperty.ImageList = null;
            this.miProperty.Index = 0;
            this.miProperty.OwnerDraw = true;
            this.miProperty.ShortcutText = "";
            this.miProperty.Text = "属性(&P)";
            this.miProperty.Click += new System.EventHandler(this.miProperty_Click);
            this.miView.ClickHandler = null;
            this.miView.EventHandlerName = null;
            this.miView.Icon = null;
            this.miView.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miView.ImageIndex = -1;
            this.miView.ImageList = null;
            this.miView.Index = 1;
            this.miView.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] { this.miLargeIcon, this.miSmallIcon, this.miList, this.miDetails });
            this.miView.OwnerDraw = true;
            this.miView.ShortcutText = "";
            this.miView.Text = "查看(&V)";
            this.miLargeIcon.ClickHandler = null;
            this.miLargeIcon.EventHandlerName = null;
            this.miLargeIcon.Icon = null;
            this.miLargeIcon.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miLargeIcon.ImageIndex = -1;
            this.miLargeIcon.ImageList = null;
            this.miLargeIcon.Index = 0;
            this.miLargeIcon.OwnerDraw = true;
            this.miLargeIcon.ShortcutText = "";
            this.miLargeIcon.Text = "大图标(&G)";
            this.miLargeIcon.Click += new System.EventHandler(this.miLargeIcon_Click);
            this.miSmallIcon.ClickHandler = null;
            this.miSmallIcon.EventHandlerName = null;
            this.miSmallIcon.Icon = null;
            this.miSmallIcon.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miSmallIcon.ImageIndex = -1;
            this.miSmallIcon.ImageList = null;
            this.miSmallIcon.Index = 1;
            this.miSmallIcon.OwnerDraw = true;
            this.miSmallIcon.ShortcutText = "";
            this.miSmallIcon.Text = "小图标(&M)";
            this.miSmallIcon.Click += new System.EventHandler(this.miSmallIcon_Click);
            this.miList.ClickHandler = null;
            this.miList.EventHandlerName = null;
            this.miList.Icon = null;
            this.miList.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miList.ImageIndex = -1;
            this.miList.ImageList = null;
            this.miList.Index = 2;
            this.miList.OwnerDraw = true;
            this.miList.ShortcutText = "";
            this.miList.Text = "列表(&L)";
            this.miList.Click += new System.EventHandler(this.miList_Click);
            this.miDetails.ClickHandler = null;
            this.miDetails.EventHandlerName = null;
            this.miDetails.Icon = null;
            this.miDetails.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miDetails.ImageIndex = -1;
            this.miDetails.ImageList = null;
            this.miDetails.Index = 3;
            this.miDetails.OwnerDraw = true;
            this.miDetails.ShortcutText = "";
            this.miDetails.Text = "详细资料(&D)";
            this.miDetails.Click += new System.EventHandler(this.miDetails_Click);
            this.miRefresh.ClickHandler = null;
            this.miRefresh.EventHandlerName = null;
            this.miRefresh.Icon = null;
            this.miRefresh.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miRefresh.ImageIndex = -1;
            this.miRefresh.ImageList = null;
            this.miRefresh.Index = 2;
            this.miRefresh.OwnerDraw = true;
            this.miRefresh.ShortcutText = "";
            this.miRefresh.Text = "刷新(&R)";
            this.miRefresh.Click += new System.EventHandler(this.miRefresh_Click);
            this.miShowDock.ClickHandler = null;
            this.miShowDock.EventHandlerName = null;
            this.miShowDock.Icon = null;
            this.miShowDock.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miShowDock.ImageIndex = -1;
            this.miShowDock.ImageList = null;
            this.miShowDock.Index = 3;
            this.miShowDock.OwnerDraw = true;
            this.miShowDock.ShortcutText = "";
            this.miShowDock.Text = "显示导航树(&D)";
            this.miShowDock.Click += new System.EventHandler(this.miShowDock_Click);
            this.miSelected.ClickHandler = null;
            this.miSelected.EventHandlerName = null;
            this.miSelected.Icon = null;
            this.miSelected.IconTransparentColor = System.Drawing.Color.FromArgb(0, 0x80, 0x80);
            this.miSelected.ImageIndex = -1;
            this.miSelected.ImageList = null;
            this.miSelected.Index = 4;
            this.miSelected.OwnerDraw = true;
            this.miSelected.ShortcutText = "";
            this.miSelected.Text = "选择(&S)";
            this.miSelected.Click += new System.EventHandler(this.miSelected_Click);
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 15);
            base.ClientSize = new System.Drawing.Size(0x27c, 0x1b2);
            base.Controls.Add(this.pnlMain);
            base.Controls.Add(this.splTree);
            base.Name = "FrmRESPicture";
            base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "图片资源";
            base.Load += new System.EventHandler(this.FrmRESPicture_Load);
            this.pnlMain.ResumeLayout(false);
            this.pnlNatural.ResumeLayout(false);
            this.gbProperty.EndInit();
            this.gbProperty.ResumeLayout(false);
            this.pnlProperty.ResumeLayout(false);
            this.gbLargeImage.EndInit();
            this.gbLargeImage.ResumeLayout(false);
            this.pnlLargeImage.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)this.pb).EndInit();
            this.pnlMiniature.ResumeLayout(false);
            base.ResumeLayout(false);
        }
        #endregion    
        private Thyt.TiPLM.UIL.Controls.GroupBoxPLM gbLargeImage;
        private Thyt.TiPLM.UIL.Controls.GroupBoxPLM gbProperty;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblAlias;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblCreateTime;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblCreator;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblDes;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblModifier;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblModifyTime;
        private Thyt.TiPLM.UIL.Controls.LabelPLM lblSize;
        private Thyt.TiPLM.UIL.Common.SortableListView lvwImage;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miAutoSize;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miCenterImage;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miDetails;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miLargeIcon;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miList;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miNormal;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miProperty;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miRefresh;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miSelected;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miShowDock;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miSmallIcon;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miStretchImage;
        private Thyt.TiPLM.CLT.UIL.DeskLib.Menus.MenuItemEx miView;
        private System.Windows.Forms.ColumnHeader picture;
        private System.Windows.Forms.ColumnHeader pictureCreateTime;
        private System.Windows.Forms.ColumnHeader pictureCreator;
        private System.Windows.Forms.ColumnHeader pictureDescrip;
        private System.Windows.Forms.ColumnHeader pictureModifier;
        private System.Windows.Forms.ColumnHeader pictureModifyTime;
        private System.Windows.Forms.ColumnHeader pictureSize;
        private Thyt.TiPLM.UIL.Controls.PanelPLM pnlLargeImage;
        private Thyt.TiPLM.UIL.Controls.PanelPLM pnlMain;
        private Thyt.TiPLM.UIL.Controls.PanelPLM pnlMiniature;
        private Thyt.TiPLM.UIL.Controls.PanelPLM pnlNatural;
        private Thyt.TiPLM.UIL.Controls.PanelPLM pnlProperty;
        private Thyt.TiPLM.UIL.Controls.SplitterPLM splPic;
        private Thyt.TiPLM.UIL.Controls.SplitterPLM splPro;
        private Thyt.TiPLM.UIL.Controls.SplitterPLM splTree;
    }
}